- web-app/js/portal/filter/BaseFilterPanel.js
- web-app/js/portal/filter/BoundingBoxFilterPanel.js
- web-app/js/portal/filter/DateFilterPanel.js
These are tidy-ups I made before working on #1517 but the bug was closed so no functional changes were made
> Tidy-ups from #1517

- web-app/js/portal/portal.js
> Delete disclaimer popup from manual data collection access

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Required to fix GA improvements vit and for portal-systest re-release
> Track selection of data collections on step 2 using google analytics

- web-app/js/portal/filter/ComboFilterPanel.js
> Always fire add event on combo select all option

- web-app/css/IMOS.css
- web-app/css/general.css
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Pull request onto Snazo branch
> Step 1 results formatting changes - Snazo

- web-app/css/general.css
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
The Download panel was more effected by the last changes than I though.
> Step 3 download formatting changes - Snazo

- src/test/javascript/portal/search/DateSelectionPanelSpec.js
- src/test/javascript/portal/search/GeoSelectionPanelSpec.js
- src/test/javascript/portal/search/SearchFiltersPanelSpec.js
- web-app/css/general.css
- web-app/js/portal/search/DateSelectionPanel.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/search/GeoSelectionPanel.js
- web-app/js/portal/search/SearchFiltersPanel.js
- web-app/js/portal/search/TermSelectionPanel.js
Icons on Facet headings - responsive design layout of search results
> Snazo Tim review changes 

- web-app/css/general.css
- web-app/js/portal/search/FacetedSearchResultsDataView.js
This is Snazo design B 
The previous commit would be considered Snazo design A
> Snazo design B

- web-app/js/portal/cart/DownloadPanelItemTemplate.js
> Share link goes to home controller rather than app root

- grails-app/controllers/au/org/emii/portal/HomeController.groovy
- grails-app/controllers/au/org/emii/portal/LandingController.groovy
- grails-app/views/_js_includes.gsp
- grails-app/views/_public_theme_includes.gsp
> Version CSS files to force re-download with new versions

- web-app/js/portal/search/FacetFilterPanel.js
Need to use dolayout if changing components on a visible panel
> Fix new search issue introduced by drilldown panel refactor

- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- src/test/javascript/portal/filter/BooleanFilterPanelSpec.js
- src/test/javascript/portal/filter/BoundingBoxFilterPanelSpec.js
- src/test/javascript/portal/filter/ComboFilterPanelSpec.js
- src/test/javascript/portal/filter/FilterGroupPanelSpec.js
- web-app/js/portal/filter/BooleanFilterPanel.js
- web-app/js/portal/filter/ComboFilterPanel.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/FilterGroupPanel.js
@anguss00 this fixes a bunch of tests which we should have updated as we did our filter work.
> Broken jasmine on geoserver filters

- get_filters.rb
- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- src/groovy/au/org/emii/portal/wms/NcwmsServer.groovy
- test/unit/au/org/emii/portal/wms/GeoserverServerTests.groovy
- web-app/js/portal/filter/FilterGroupPanel.js
- web-app/js/portal/filter/FilterService.js
This adds a feature toggle to select between loading filters from the database and loading them from XML files/GeoServer. For now we use XML files (ie. not GeoServer) but that can be easily changed when the new GeoServer plugin changes have been made.
> Geoserver filters feature toggle

- src/test/javascript/portal/filter/BooleanFilterPanelSpec.js
- web-app/js/portal/filter/BooleanFilterPanel.js
I got carried away fixing Jasmine tests. In 'fixing' this test I had actually broken the real behaviour. So it is now (un)fixed (again).
> Undo fix for Jasmine test.

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- src/test/javascript/portal/filter/BooleanFilterPanelSpec.js
- src/test/javascript/portal/filter/ComboFilterPanelSpec.js
- src/test/javascript/portal/filter/DateFilterPanelSpec.js
- src/test/javascript/portal/filter/FilterGroupPanelSpec.js
- test/unit/au/org/emii/portal/wms/GeoserverServerTests.groovy
- web-app/js/portal/filter/BaseFilterPanel.js
- web-app/js/portal/filter/BooleanFilterPanel.js
- web-app/js/portal/filter/ComboFilterPanel.js
- web-app/js/portal/filter/DateFilterPanel.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/FilterGroupPanel.js
- web-app/js/portal/filter/GeometryFilterPanel.js
- web-app/js/portal/filter/NumberFilterPanel.js
This work is basically all moving and removing. Nothing new/changed.
> Filters refactor

- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/controllers/au/org/emii/portal/FilterController.groovy
- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- grails-app/controllers/au/org/emii/portal/MarvlController.groovy
- grails-app/controllers/au/org/emii/portal/SearchController.groovy
- grails-app/controllers/au/org/emii/portal/SnapshotController.groovy
- grails-app/controllers/au/org/emii/portal/SystemController.groovy
- grails-app/utils/au/org/emii/portal/HttpUtils.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/WfsScannerControllerTests.groovy
- test/unit/au/org/emii/portal/WmsScannerControllerTests.groovy
Some tidy-up in LayerController from Filters work
> Moar filter refactoring

- README.md
* Removed references to scanners and spatial search
* Removed listed 'features' that no longer exist
* Updated list of configuration overrides
> Update README for current features/requirements

- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
Tests run nice now - no ugly exceptions polluting the output
> eliminate xml exception logging

- grails-app/conf/Config.groovy
> remove redundant config snippets

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
Reinstate some changes which were lost in a rebase.
Also, added a default HTTP status for getMetadataAbstract as there were some code paths in which it wasn't set.
> Fix rebase problem

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- src/test/javascript/portal/filter/BooleanFilterPanelSpec.js
- src/test/javascript/portal/filter/ComboFilterPanelSpec.js
- src/test/javascript/portal/filter/DateFilterPanelSpec.js
- src/test/javascript/portal/filter/FilterGroupPanelSpec.js
- src/test/javascript/portal/filter/GeometryFilterPanelSpec.js
- src/test/javascript/portal/filter/NumberFilterPanelSpec.js
- web-app/js/portal/details/SubsetPanel.js
- web-app/js/portal/filter/ui/BaseFilterPanel.js
- web-app/js/portal/filter/ui/BooleanFilterPanel.js
- web-app/js/portal/filter/ui/ComboFilterPanel.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
- web-app/js/portal/filter/ui/EmptyFilterPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/filter/ui/GeometryFilterPanel.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
- web-app/js/portal/filter/ui/ResettableDate.js
Created a new 'filter.ui' package in Javascript land for the UI elements of filters. Making way for a bunch of new files in the 'filter' package.
> Moved filter panels into a UI package

- web-app/js/portal/lang/en.js
> Change label on layer selector to read "Subsetting data collection:"

- .gitignore
- README.md
- grails-app/conf/Config.groovy
allow loading of local config from grails-app/conf/Config.local.groovy if it
exists when in development mode. easier to amend config without needing to
touch the main Config.groovy
> local config at Config.local.groovy

- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/details/NcWmsPanel.js
* reset to original extent when clicked on reset
@dnahodil Reset button does work for me - as expected. I kindly added all the new lines.
> reset button in NcWmsPanel works

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/js/portal/filter/ui/BooleanFilterPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
> Issue #1709

- src/test/javascript/portal/filter/DateFilterSpec.js
- web-app/js/portal/filter/DateFilter.js
> Step 3 uses filter label when more than one time filter

- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/services/au/org/emii/portal/GogoduckService.groovy
- src/test/javascript/portal/cart/DownloaderSpec.js
- src/test/javascript/portal/cart/GogoduckDownloadHandlerSpec.js
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/GogoduckServiceTests.groovy
- web-app/js/portal/cart/Downloader.js
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/lang/en.js
* Server side parsing of GGD returned JSON + formatting HTML returned to client (together with https://github.com/aodn/go-go-duck/pull/100)
* Client side displaying of the returned HTML in the alert box
This will enable users to have a link in the alert box after a job submission was successful.
> gogoduck link

- grails-app/views/home/index.gsp
**DO NOT MERGE**
Hardcoded and ugly, but a significantly simpler fix I think.
@pmbohm @dnahodil
> issue 1723 proof of concept fix

- src/groovy/au/org/emii/portal/HostVerifier.groovy
> allow multiple base layer geoservers

- web-app/css/imosTheme.css
Been driving me mad for a while
> Fix ugly separator on topLinks link items

- grails-app/conf/Config.groovy
- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/search/FreeTextSearchPanelSpec.js
- src/test/javascript/portal/search/SearchFiltersPanelSpec.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FreeTextSearchPanel.js
- web-app/js/portal/search/SearchFiltersPanel.js
can specify facets in server config
makes it easier to choose which facets to load for which portals. easier to incorporate things like https://github.com/aodn/aodn-portal/pull/1745
@markhepburn FYI
> refactor search facets creation

- src/test/javascript/portal/filter/ui/NumberFilterPanelSpec.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/utils/trackUsage.js
> Validate operator before attempting to update number filter

- web-app/js/portal/filter/ui/ResettableDate.js
> Set standard date picker width

- src/test/javascript/portal/search/SearchBodyPanelSpec.js
- web-app/css/general.css
- web-app/js/portal/search/FacetedSearchResultsPanel.js
- web-app/js/portal/search/SearchBodyPanel.js
Fixes #1790
This change gives different widths to the grey title bars on step 1 and 3 (previously they had been the same).
> Adjust width of step 1 results titles

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/details/SpatialConstraintDisplayPanelSpec.js
- src/test/javascript/portal/filter/validation/SpatialConstraintValidatorSpec.js
- src/test/javascript/portal/ui/openlayers/control/SpatialConstraintSpec.js
- web-app/js/portal/filter/validation/SpatialConstraintValidator.js
- web-app/js/portal/prototypes/OpenLayers.js
- web-app/js/portal/search/FacetMapPanel.js
- web-app/js/portal/ui/openlayers/SpatialConstraintMap.js
- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
> Issue #1770

- web-app/css/general.css
Adding this back in fixes the page layout problem on the landing page. Fixes #1801.
@pmbohm I couldn't see any problems with re-adding this so I'm not sure why it was removed. Is there anything you would expect to be a problem?
> Fixed width for landing page container

- web-app/css/general.css
- web-app/js/portal/details/NCWMSColourScalePanel.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/lang/en.js
Layer visibility functionality was removed by #1804 
The zoom to layer functionality was left out of the step2 accordion changes #1774
> Add map layer visibility and zoom to layer to step2 layer tabs

- web-app/js/portal/search/FacetMapPanel.js
> Add spatial constraint validator to geometry facet

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/css/general.css
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/details/SpatialSubsetControlsPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/filter/ui/ResettableDate.js
- web-app/js/portal/lang/en.js
This is all about making the reset link (some buttons) appear to be uniform throughout the site.
It is a foreign order from @pblain
> Clearer clear and reset on step2

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- web-app/js/portal/data/LayerStore.js
This PR tidies a few things which were intended to be cleaned-up when no-db arrived.
> Tidy of some remaining pre-'No DB' code

- web-app/js/portal/details/SubsettingPanel.js
- web-app/js/portal/prototypes/NonCollapsingAccordionLayout.js
Surplus expands and circular listeners removed
> fixes #1821 - layout manager internally properly updated when collections are deleted

- grails-app/conf/Config.groovy
- grails-app/views/landing/index.gsp
@pmbohm I noticed that these links (landing page footer and general footer links) were not marked as external. Is it worth bringing them into line?
> Mark links as external

- grails-app/conf/Config.groovy
> Fix broken acknowledgment and disclaimer links

- .travis.yml
> Stop the gloats

- web-app/js/ext-3.3.1/ext-all-debug-w-comments.js
@danfruehauf apparently Jasmine uses this file for Ext so I've disabled the flash detection here as well.
> Disable flash detection in ext-deb-all-w-comments.js

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/PortalEvents.js
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/prototypes/OpenLayers.js
- web-app/js/portal/ui/openlayers/MapOptions.js
I have to admit, I'm not overly happy with 642a4ae, but it does seems to work ok for me.
> Issue 1835

- web-app/css/general.css
- web-app/js/portal/search/FreeTextSearchPanel.js
Take 2. Items align vertically now. Complete PITA.
Fixes #1836
> Issue 1836

- grails-app/taglib/au/org/emii/portal/MessageOfTheDayTagLib.groovy
did not have portalBranding defined in file
> amend b645ac0, fix motd from brandingBase

- src/test/javascript/portal/data/DataCollectionSpec.js
> Move spec into correct suite

- grails-app/conf/Config.groovy
- src/test/javascript/portal/ui/MapPanelSpec.js
- src/test/javascript/portal/ui/VisualisePanelSpec.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/ui/MapPanel.js
This functionality is no longer available from the UI.
> Removed some unused auto zoom code

- src/test/javascript/portal/data/GeoNetworkRecordFetcherSpec.js
- web-app/js/portal/data/GeoNetworkRecordFetcher.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/ui/MainPanel.js
* fix #1874, show message box when invalid data collection uuid is
requested
* land user on step 1 if data collection from url could not be
loaded
* if at least one collection was loaded, land in step 2
> show error when loading invalid data collection

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/data/DataCollectionStore.js
- web-app/js/portal/data/GeoNetworkRecordStore.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
This tidies some methods which were in the wrong place or which seemed to perform an operation an Ext Store should already be able to do.
> Tidy store operations

- src/test/javascript/portal/data/LayerStoreSpec.js
- web-app/js/portal/data/LayerStore.js
> Do not check for duplicates before adding layer to LayerStore

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- src/test/javascript/portal/cart/DownloadPanelSpec.js
- src/test/javascript/portal/details/LayerControlPanelSpec.js
- src/test/javascript/portal/details/StylePanelSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/details/LayerControlPanel.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/utils/trackUsage.js
Addresses some of the google analytics metrics we're lacking. See also #1878.
> moar google analytics

- web-app/js/portal/search/FreeTextSearchPanel.js
Created an empty template for this panel's tools
Fixes #1891
> Hide toggle arrow for FreeTextSearchPanel

- web-app/css/general.css
- web-app/js/portal/search/GeoSelectionPanel.js
> GeoSelection Facet buttons overlaying the map

- web-app/js/portal/details/DataCollectionDetailsPanel.js
> Change usage of old getLayerState() to new getLayerAdapter()

- src/test/javascript/portal/ui/MapPanelSpec.js
- web-app/js/portal/data/DataCollectionLayerAdapter.js
- web-app/js/portal/ui/MapPanel.js
Probably hanging around from the days where the data driving the portal (i.e. geonetwork/geoserver config) was not as strictly controlled.
> Removed some (hopefully) unnecessary code

- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/details/NcWmsPanel.js
> #1870 - On reset apply the filter values from controls

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/data/DataCollectionLayerAdapterSpec.js
- src/test/javascript/portal/data/DataCollectionSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/filter/FilterServiceSpec.js
- src/test/javascript/portal/filter/FilterSpec.js
- src/test/javascript/portal/filter/ui/DateFilterPanelSpec.js
- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- src/test/javascript/portal/filter/ui/NumberFilterPanelSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- src/test/javascript/portal/utils/ObservableUtilsSpec.js
- web-app/js/portal/data/DataCollection.js
- web-app/js/portal/data/DataCollectionLayerAdapter.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/FilterService.js
- web-app/js/portal/filter/ui/BaseFilterPanel.js
- web-app/js/portal/filter/ui/BooleanFilterPanel.js
- web-app/js/portal/filter/ui/ComboFilterPanel.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/filter/ui/GeometryFilterService.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
- web-app/js/portal/prototypes/OpenLayers.js
- web-app/js/portal/utils/ObservableUtils.js
These changes make it so that DataCollection loads its own Filters as it is created and the GroupFilterPanel only listens for events (previously it initiated the loading, itself). Also, Filters now fire an even when their value is changed.
> Data Collection loads filters rather than UI component

- web-app/js/portal/ui/openlayers/MapOptions.js
The MapPanel needs to be accessible via the Map.
> Fix for #1939

- src/test/javascript/portal/search/FreeTextSearchPanelSpec.js
- web-app/js/portal/search/FreeTextSearchPanel.js
transform to lower case any search term in free text search panel
> fix #1942 - send GA for free text in lower case

- web-app/js/portal/details/NcWmsPanel.js
use geometry from event for ncwms layers
> fix #1944 - use geometry from event

- src/test/javascript/portal/details/LayerControlPanelSpec.js
- web-app/js/portal/details/LayerControlPanel.js
Fixes https://github.com/aodn/aodn-portal/issues/1951
> Issue 1951

- src/test/javascript/portal/data/MetadataRecordFetcherSpec.js
- web-app/js/portal/data/MetadataRecordFetcher.js
> Don't try to use metadataRecord until we know that one has been found

- src/test/javascript/portal/data/MetadataRecordFetcherSpec.js
- web-app/js/portal/data/MetadataRecordFetcher.js
> Bookmark hashes now stripped

- web-app/css/general.css
> Viewport Buttons active area matches text

- src/test/javascript/portal/common/LayerDescriptorSpec.js
- web-app/js/portal/data/Server.js
- web-app/js/portal/ui/openlayers/LayerParams.js
Removed unused variables and tests for unused behaviour
> Some tidy up

- src/test/javascript/portal/ui/NavigableCardLayoutSpec.js
- web-app/js/portal/ui/NavigableCardLayout.js
> Viewport Step 123 navigation buttons - no action when selected card already active

- src/test/javascript/portal/cart/DownloadPanelSpec.js
- src/test/javascript/portal/prototypes/ArraySpec.js
- web-app/css/general.css
- web-app/js/portal/cart/BodaacDownloadHandler.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/cart/WfsDownloadHandler.js
- web-app/js/portal/common/helpers.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/prototypes/Array.js
To test use Geonetwork-123 and uuid=0a21e0b9-8acb-4dc2-8c82-57c3ea94dd85
> Download links grouped by WFS layer

- web-app/js/portal/cart/DownloadPanel.js
> Bug fix for WPS DownloadPanel confirmDownload call

- grails-app/conf/Config.groovy
- src/test/javascript/portal/data/MetadataRecordStoreSpec.js
- src/test/javascript/portal/details/InfoPanelSpec.js
- web-app/css/general.css
- web-app/js/portal/data/MetadataRecord.js
- web-app/js/portal/details/InfoPanel.js
- web-app/js/portal/lang/en.js
A solution for https://github.com/aodn/aodn-portal/issues/1771
Sorts external links according to the currently available protocols;
Natalia has created a report which shows the possible protocols are less numerous than first thought. The email is added
> External links re-grouped by available protocols

- grails-app/conf/BuildConfig.groovy
- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/WpsController.groovy
- grails-app/i18n/messages.properties
- grails-app/services/au/org/emii/portal/WpsService.groovy
- grails-app/taglib/au/org/emii/portal/LabelledContentTagLib.groovy
- grails-app/views/taglib/_labelledContentTemplate.gsp
- grails-app/views/wps/jobComplete.gsp
- grails-app/views/wps/jobRegistered.gsp
- grails-app/views/wps/show.gsp
- pom.xml
- test/unit/au/org/emii/portal/WpsControllerTests.groovy
- web-app/css/imosTheme.css
Access the page with URL of the form:
http://localhost:8080/aodn-portal/wps/jobReport?server=\<WPS server\>&uuid=\<UUID\>
e.g.:
http://localhost:8080/aodn-portal/wps/jobReport?server=http%3A%2F%2Fgeoserver-systest.aodn.org.au%2Fgeoserver%2Fows&uuid=e8c4ce84-3e18-4c37-9790-746dcf2c79cb
> Wps status page

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- web-app/js/portal/cart/DownloadEstimator.js
Fix download estimator - can now find element to update after
download estimator returns
> Fix #1998 - use correct uuid

- src/test/javascript/portal/filter/ui/DateFilterPanelSpec.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
This is another way to fix #1988
> Issue #1988 alternative

- grails-app/conf/Config.groovy
- src/test/javascript/portal/service/CatalogSearcherSpec.js
- web-app/js/portal/service/CatalogSearcher.js
Disable/enable GN link monitor from config
> Feature toggle for GN link monitor

- grails-app/services/au/org/emii/portal/WpsService.groovy
- grails-app/views/wps/_asyncRequest.xml.gsp
- src/test/javascript/portal/cart/WpsDownloadHandlerSpec.js
- test/unit/au/org/emii/portal/WpsServiceTests.groovy
- web-app/js/portal/cart/WpsDownloadHandler.js
The client's request now aligns with what the server expects.  Conversion to and from JSON has been removed, as it is just complicating things (IMO) for no benefit.
> WPS client server integration

- grails-app/conf/Config.groovy
@atkinsn discovered an additional protocol is being used by metadata
> Added to metadataProtocols in config.groovy

- grails-app/services/au/org/emii/portal/WpsService.groovy
- grails-app/views/wps/_asyncRequest.xml.gsp
- src/test/javascript/portal/cart/WpsDownloadHandlerSpec.js
- web-app/js/portal/cart/WpsDownloadHandler.js
To test:
Configuration:
1. run up geoserver using master/HEAD from geoserver-build (probably easiest to do so by dropping built war in to PO box tomcat)
1. configure portal to use catalogue-rc (`geonetwork.url = "http://catalogue-rc.aodn.org.au/geonetwork"`)
1. Hack "/etc/hosts" to point geoserver-rc to your own instance
In the portal:
1. In Step 1, facet filter by Keyword "test wps"
1. Select the "TEST WPS ..." collection
1. In Step 2, configure a spatial filter
1. In Step 3, select "Download Later"
> Notification callback

- src/test/javascript/portal/search/FreeTextSearchPanelSpec.js
- web-app/js/portal/search/FreeTextSearchPanel.js
A small but persistent annoyance.
> Focus the text field when the free text search facet is expanded

- grails-app/conf/UrlMappings.groovy
- grails-app/controllers/au/org/emii/portal/WpsController.groovy
- test/unit/au/org/emii/portal/WpsControllerTests.groovy
... just like everything else.
> Proxy netcdf file downloads

- grails-app/conf/Config.groovy
- src/test/javascript/portal/search/DateSelectionPanelSpec.js
- src/test/javascript/portal/search/GeoSelectionPanelSpec.js
- src/test/javascript/portal/search/SearchFiltersPanelSpec.js
The 'hierarchical' attribute is not used anywhere in code so removing from config
> Remove unused attribute

- web-app/js/portal/details/StylePanel.js
> Errant trailing comma broke GetLegendGraphic requests

- grails-app/controllers/au/org/emii/portal/WpsController.groovy
- grails-app/views/wps/show.gsp
- src/test/javascript/portal/cart/DownloaderSpec.js
- web-app/js/portal/cart/Downloader.js
> Better async job creation error message in popup. 

- grails-app/conf/Config.groovy
Fixes #2106
Fixes https://github.com/aodn/backlog/issues/270
>  Allow onlineResources with protocol 'WWW:LINK-1.0-http--downloaddata' on Step 3

- web-app/js/portal/search/GeoSelectionPanel.js
> Reset to default bbox on geo filter when all filters are reset

- web-app/js/portal/lang/en.js
Just a little adjustment requested by @pblain
> Download confirmation: boilerplate format tweak

- web-app/js/portal/lang/en.js
> Open jurisdiction links in new tab in step 3 download confirmation

- grails-app/services/au/org/emii/portal/BulkDownloadService.groovy
> Calculate and return the total bytes read for each url list download

- web-app/css/general.css
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
> Step 1 icons using the iconSourceUuid from Geonetwork.

- web-app/css/general.css
- web-app/js/portal/search/FacetedSearchResultsDataView.js
The icons are too be re-supplied and/or photoshopped by us to a uniform look for all contributors. For now it needs to be hidden
> remove greyscale effect and temporarily hide icons for now

- grails-app/controllers/au/org/emii/portal/WpsController.groovy
- grails-app/views/wps/_asyncRequest.xml.gsp
- src/groovy/au/org/emii/portal/proxying/ProxiedRequest.groovy
- test/unit/au/org/emii/portal/proxying/ProxiedRequestTests.groovy
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/NetcdfSubsetServiceDownloadHandler.js
- web-app/js/portal/cart/PointCSVDownloadHandler.js
Requires https://github.com/aodn/geoserver-build/pull/141
> Addresses #2224 - proxy content type of WPS outputs

- grails-app/conf/Config.groovy
- grails-app/services/au/org/emii/portal/WpsService.groovy
- grails-app/views/wps/jobComplete.gsp
- grails-app/views/wps/jobFailed.gsp
- grails-app/views/wps/jobRegistered.gsp
Corresponding Chef changes wont be required by AODN but this is could be of interest to @markhepburn and or @fxmzb123  ?
> Fixes 2230

- web-app/js/portal/details/NcWmsPanel.js
> Set autoHeight for ncwms panels to avoid accordion gaps

- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- test/unit/au/org/emii/portal/DownloadControllerTests.groovy
> Ignore absolute URL's from database when downloading list of URL's

- selenium/src/test/java/au/org/emii/portal/tests/BrowserStackTest.java
- selenium/src/test/java/au/org/emii/portal/tests/ImosLinkCheckTest.java
- selenium/src/test/java/au/org/emii/portal/tests/ImosLogoCheckTest.java
- selenium/src/test/resources/testng.xml
> Updated selenium config and removed wait

- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/filter/ui/DateFilterPanelSpec.js
- src/test/javascript/portal/ui/openlayers/layer/NcWmsSpec.js
- web-app/js/ext-ux/form/DateTime.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/form/UtcExtentDateTime.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/utils/moment.min.js
- web-app/js/portal/visualise/animations/TemporalExtent.js
> Fixes #2249 date range logic validation

- web-app/css/general.css
I realized it looked too cheezy for 2016. 
Next step 100% bootstrap
> Simpler message box CSS when no collections are loaded

- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/ui/openlayers/control/SpatialConstraintSpec.js
- web-app/css/AODNTheme.css
- web-app/js/portal/details/BoxDisplayPanel.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/details/PointTimeSeriesPanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
Includes the approval of @pblain
> Fixes #2265. Links resets all Spatial subsets or all subset filters including spatial

- selenium/src/test/java/au/org/emii/portal/tests/BaseTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/AcknowledgementTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/AodnLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/ContactLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/ContributingLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/DisclaimerLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/ImosLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/OceanCurrentLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/PortalTest.java
- selenium/src/test/java/au/org/emii/portal/utils/WebElementUtil.java
- selenium/src/test/resources/log4j.properties
- selenium/src/test/resources/testng.xml
> Test rail 1

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/views/_js_includes.gsp
- test/unit/au/org/emii/portal/DownloadControllerTests.groovy
- web-app/js/portal/cart/FileListDownloadHandler.js
- web-app/js/portal/filter/combiner/FileListCqlBuilder.js
**URL:** _http://geoserver-123.aodn.org.au/geoserver/ows?typeName=aodn_mhl_sst_map&propertyName=url_
typeName is layer
propertyName is the database column name with the urls
**Protocol:** _AODN:FILE-list_
**Name of the resource:** _CSV_
**Description:** _The "File List" is a WFS service that returns a list of OpenDAP URLs matching a query._
> Added Download handler for differt file types

- grails-app/conf/Config.groovy
> Updated catalogue URL

- web-app/css/general.css
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/ui/openlayers/layer/NcWms.js
> Fixes #2286 -traps errors and disables timeSelect buttons when extent is not loaded

- web-app/js/portal/cart/FileListDownloadHandler.js
@jonescc  Ready for review :+1:
> Download options update

- web-app/js/portal/details/NcWmsPanel.js
> Fix to display correct time #2279

- grails-app/conf/Config.groovy
Resolves https://github.com/aodn/aodn-portal/issues/2334
> remove 'target=_blank' from Contact mailto: link

- grails-app/services/au/org/emii/portal/WpsService.groovy
[Portal PR](https://github.com/aodn/aodn-portal/pull/2331)
[Chef PR](https://github.com/aodn/chef/pull/399)
[Chef-Private PR](https://github.com/aodn/chef-private/pull/2079)
> Added bcc email for error emails

- web-app/js/portal/details/PointTimeSeriesPanel.js
- web-app/js/portal/ui/FeatureInfoPopup.js
The value of parameter I was not an integer and therefore some requests were failing.
**Invalid Request**
`http://geoserver-systest.aodn.org.au/geoserver/ncwms?LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=ncwms&REQUEST=GetFeatureInfo&STYLES=&QUERYABLE=true&CRS=EPSG%3A%204326&TIME=2016-09-27T22%3A00%3A00.000Z&BBOX=135.999756%2C-41.386475%2C145.83252%2C-34.19043&INFO_FORMAT=text%2Fxml&QUERY_LAYERS=acorn_hourly_avg_bonc_nonqc_timeseries_url%2Fsea_water_velocity&FEATURE_COUNT=1&SRS=EPSG%3A%204326&WIDTH=895&HEIGHT=655&X=205.00000000045532&Y=338&I=205.00000000045532&J=338&BUFFER=10`
`http://thredds-systest.aodn.org.au/thredds/wms/IMOS/ACORN/gridded_1h-avg-current-map_non-QC/ …
> Rounding off location co-ordinates

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
> Fix for issue #2352

- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/lang/en.js
Fixes [#2342](https://github.com/aodn/aodn-portal/issues/2342) 
Related [PR](https://github.com/aodn/geoserver-build/pull/176)
> Error message for no data

- grails-app/views/wps/show.gsp
> Adjusted timezone 

- web-app/css/general.css
> Fix for #2337

- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/lang/en.js
This reverts commit 7f0c087fc7267475845d58d332ba36f7aa7877a2.
Requires further work
> Revert "Error message for no data"

- web-app/js/portal/details/NcWmsPanel.js
> Fixes 'Next time period' button and made time dropdown collapsable

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/lang/en.js
> Updated the logic to calculate the intersect

- grails-app/conf/Config.groovy
> Add wps file expiry to default config for portal

- README.md
DO NOT MERGE
Requires further information/input
> Update out-dated information

- web-app/js/portal/details/PointTimeSeriesPanel.js
[VIT-5](https://github.com/aodn/VIT/issues/5)
> Fix for VIT-5

- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/visualise/animations/TemporalExtentSpec.js
- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
Now that I'm going to have to use Chrome, I want this noise gone
> Console error fixes

- grails-app/conf/Config.groovy
- src/groovy/au/org/emii/portal/UniqueFilenameGenerator.groovy
- test/unit/au/org/emii/portal/DepthControllerTests.groovy
- test/unit/au/org/emii/portal/MarvlControllerTests.groovy
- test/unit/au/org/emii/portal/UniqueFilenameGeneratorTests.groovy
urlListDownloadSubstitutions updated for development.
Tested with zip download with .../search?uuid=60160b01-8ffc-45ce-a6f4-ee70ce391ec6
> Issue 2400 fixed

- selenium/src/test/java/au/org/emii/portal/tests/step1/PaginateForwardInResults.java
- selenium/src/test/java/au/org/emii/portal/utils/PortalUtil.java
- selenium/src/test/java/au/org/emii/portal/utils/WebElementUtil.java
https://aodn.testrail.com/index.php?/cases/view/15
> Paginate forward in results

- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/lang/en.js
Separate download panel message where temporal extent was not filtered by user
> fixes #2409 

- selenium/src/test/java/au/org/emii/portal/tests/landing/AcknowledgementTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/ContributingLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/landing/DisclaimerLinkTest.java
- selenium/src/test/java/au/org/emii/portal/tests/step1/HelpLinkTest.java
- selenium/src/test/java/au/org/emii/portal/utils/SeleniumUtil.java
- selenium/src/test/resources/testng.xml
[Related issue](https://github.com/aodn/issues/issues/14)
> Skipping tests pointing to help.aodn.org.au

- grails-app/views/_js_includes.gsp
- web-app/js/portal/search/FacetedSearchResultsPanel.js
- web-app/js/portal/search/PagingToolbar.js
> Create local PagingToolbar.js so that the refresh icon can be changed

- selenium/src/test/java/au/org/emii/portal/tests/step1/FacetTest.java
> Revert "Organisation facet selenium test"

- grails-app/views/robots.gsp
Reverts aodn/aodn-portal#2443
Sounds like this needs to wait for input from @pblain.
> Revert "Sitemap Url as text file"

- selenium/src/test/java/au/org/emii/portal/tests/step1/FacetTest.java
Check that the results returned from selecting an organisation matches the number in the list of organisations
> Add Selenium Test for organisation results count

- web-app/js/portal/cart/DownloadPanelItemTemplate.js
Prioritizing the error message - spatial filter out of range of the collection
> Fixes #2435

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- web-app/js/portal/cart/ShapeFileDownloadHandler.js
- web-app/js/portal/filter/combiner/ShapeFileCqlBuilder.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/prototypes/OpenLayers.js
For testing search for record with UUID **c1344e70-480e-0993-e044-00144f7bc0f4** in portal
I have manually added shape file online resource for the following record.
http://catalogue-systest.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=c1344e70-480e-0993-e044-00144f7bc0f4
Transformation update for geonetwork record with UUID c1344e70-480e-0993-e044-00144f7bc0f4 for systest
Related [PR](https://github.com/aodn/schema-plugins/pull/39/files)
> Download shape file

- selenium/src/test/java/au/org/emii/portal/tests/step1/FacetTest.java
Had done the maths wrong on the expected number of results pages - didn't work with numbers divisible by ten.
> Selenium Fix for organisation facet test.

- grails-app/conf/Config.groovy
- grails-app/services/au/org/emii/portal/ProxyRedirectService.groovy
- src/groovy/au/org/emii/portal/proxying/ProxiedRequest.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- test/unit/au/org/emii/portal/ProxyRedirectServiceTests.groovy
- test/unit/au/org/emii/portal/proxying/ProxiedRequestTests.groovy
- web-app/js/portal/ui/openlayers/LayerOptions.js
Review but don't merge, since the gutter change will break squid caching (I think).
> Support proxy redirection and eliminate tile gutter

- selenium/src/test/java/au/org/emii/portal/tests/step1/FacetUntickTest.java
> The results were taking too long to load sometimes (~5seconds)

- web-app/js/portal/data/MetadataRecord.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Handle the case where metadata lists a non-recognized platform before any recognized platform
> Fixes #2502

- web-app/js/portal/ui/openlayers/layer/NcWms.js
> Trigger event 'temporalextentloaded' only when necessary

- web-app/css/general.css
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Fixes #2507  
Tested on BrowserStack OS Windows 7 FireFox 54
> Fix the un-expand issue for firefox

- grails-app/conf/Config.groovy
- src/groovy/au/org/emii/portal/proxying/ExternalRequest.groovy
- src/groovy/au/org/emii/portal/proxying/ProxiedRequest.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- test/unit/au/org/emii/portal/proxying/ProxiedRequestTests.groovy
fixes https://github.com/aodn/aodn-portal/issues/2534
> Fixes 2534 by introducing a read timeout on openConnection in portal proxy

- web-app/js/portal/mainMap/map.js
Fixed (and tightened) dodgy jQuery selector
> fixes #2551

- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- src/test/javascript/portal/ui/openlayers/control/SpatialConstraintSpec.js
- web-app/js/portal/details/SpatialConstraintDisplayPanel.js
- web-app/js/portal/search/GeoFacetMapToolbar.js
- web-app/js/portal/ui/MapPanel.js
- web-app/js/portal/ui/openlayers/SpatialConstraintMap.js
- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
Show geometry as a point list (if geometry is set) when selecting polygon Spatial Subset drawing
> Fixes #2537

- web-app/js/portal/jquery.js
@akashisama This is ready for local browser stack testing
> Possible :) fixes #2542

- selenium/src/test/java/au/org/emii/portal/tests/step3/DownloadOptionsTest.java
Fixes https://github.com/aodn/aodn-portal/issues/2543
> Fix issue 2543

- grails-app/conf/Config.groovy
Schema Plugins [PR](https://github.com/aodn/schema-plugins/pull/51)
Portal [PR](https://github.com/aodn/aodn-portal/pull/2565)
> Fix for issue#2564

- selenium/src/test/java/au/org/emii/portal/tests/step1/FacetDateTest.java
- selenium/src/test/java/au/org/emii/portal/utils/PortalUtil.java
https://github.com/aodn/aodn-portal/issues/2546
> Fix for issue 2546

- selenium/src/test/java/au/org/emii/portal/utils/SeleniumUtil.java
See https://github.com/aodn/aodn-portal/pull/2588 and https://github.com/aodn/aodn-portal/issues/2548#issuecomment-352963115
Fixes #2548
> Don't validate links to metadata

- grails-app/views/landing/index.gsp
- web-app/css/AODNLanding.css
Part fix https://github.com/aodn/backlog/issues/767
> Re-ordering and fixing width of contributor logos. 

- grails-app/views/landing/index.gsp
- web-app/css/AODNLanding.css
Small screens will fold the logos to the bottom of page.
@pblain approved
> Re-ordering of logos and text sections on landing page

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/filter/combiner/FiltersWithValuesCqlBuilder.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/prototypes/OpenLayers.js
fixes https://github.com/aodn/backlog/issues/774
> Empty download check fix

- selenium/src/test/java/au/org/emii/portal/tests/step1/ClearFacetTest.java
selenium test for [Clear a Facet](https://aodn.testrail.com/index.php?/cases/view/76&group_by=cases:section_id&group_order=asc&group_id=4)
I've updated the name of the test in TestRail and appended '- Selenium Test Added'. Wasn't sure exactly whether this should be done before this PR is merged or after but I didn't want it to get overlooked so I just did it.
> added new selenium test for clearing date and map facets

- selenium/src/test/java/au/org/emii/portal/tests/step1/IndicateResultAddedToMap.java
this is a test for [this case case in TestRail](https://aodn.testrail.com/index.php?/cases/view/81)
> added selenium test: Indicate Result Added To Map

- src/test/javascript/portal/cart/GogoduckDownloadHandlerSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/spec_helper.js
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/NcWmsInjector.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/SearchFiltersPanel.js
- web-app/js/portal/ui/TimeRangeLabel.js
- web-app/js/portal/ui/openlayers/layer/NcWms.js
For https://github.com/aodn/backlog/issues/718
Reads the z-axis information from the getMetadata request and creates a depth/elevation filter if required. 
The selected z-axis is applied to the map by adding "ELEVATION=[a value]" to getMap requests.
> Handling depth filters

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
> Fixes #2607

- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/details/ZAxisPickerContainer.js
- web-app/js/portal/lang/en.js
Fixes https://github.com/aodn/issues/issues/167
> Adjust z-axis values for positive up and down axis conventions

- selenium/src/test/java/au/org/emii/portal/tests/step1/ClearFacetTest.java
Selenium fix for this iteration
> ClearFacetTest now waits for occasional slow loading of Geonetwork

- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/PointCSVDownloadHandler.js
Fixes https://github.com/aodn/aodn-portal/issues/2618
> Test filter label for positive up and down when determining z filters

- web-app/js/portal/ui/TimeRangeLabel.js
> Fixes #2620 - no need to start with map loading message

- selenium/src/test/java/au/org/emii/portal/tests/step1/UnhealthyCollectionsRemoved.java
selenium-upped this test rail case: https://aodn.testrail.com/index.php?/cases/view/11644
(I've updated the title of the test rail case with '- Selenium Test Added')
> added test for unhealthy collections

- web-app/js/portal/details/NcWmsPanel.js
> fixes #2630 validates ncwms datetimepickers before adding values to filters

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/DepthController.groovy
- test/unit/au/org/emii/portal/DepthControllerTests.groovy
- web-app/js/portal/ui/FeatureInfoPopup.js
> Depth service now from Geoserver

- selenium/src/test/java/au/org/emii/portal/tests/step1/ClearFreeTextSearch.java
New selenium test regarding[ this test case](https://aodn.testrail.com/index.php?/tests/view/38201&group_by=cases:section_id&group_order=asc&group_id=4)
I've already updated the title of the test case in testrail.com with '_- Selenium Test Added_'
> clear free text search

- src/test/javascript/portal/details/StylePanelSpec.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/ui/openlayers/layer/NcWms.js
Fixes https://github.com/aodn/chef-private/issues/2811 (actually portal bug)
> Handle numColorBands in style legend

- web-app/js/ext-ux/Hyperlink/Hyperlink.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FreeTextSearchPanel.js
- web-app/js/portal/utils/trackUsage.js
Fixes the issue without any extra clutter
> Fixes #2488 by making the search icon functional

- web-app/js/portal/search/FacetedSearchResultsMiniMap.js
- web-app/js/portal/utils/trackUsage.js
Fixes https://github.com/aodn/issues/issues/220
> Center on 180w when datasets cover world or cross antemeridian

- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
fixes: https://github.com/aodn/aodn-portal/issues/2661
> fixes #2261 incorrect zindex on drawn rectangle

- .github/ISSUE_TEMPLATE.md
This template automatically populates issues in GitHub
> Creates ISSUE_TEMPLATE.md

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
getFeature count check against map layer with only map layer cql parameters
> fixes #2688

- grails-app/conf/Config.groovy
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/InternalAsyncDownloadHandler.js
- web-app/js/portal/cart/PointCSVDownloadHandler.js
Send requested aggregation filename.
> Request new ZIPped output from AWS-WPS.

- grails-app/conf/Config.groovy
Config to include dataLayers from geoserver static. Can be merged separately from https://github.com/aodn/aodn-portal/pull/2717 without affecting production
For 
https://github.com/aodn/backlog/issues/919
> New DataLayers config. Added Australian Marine parks data layer

- grails-app/views/_js_includes.gsp
- pom.xml
- src/test/javascript/portal/details/LayerControlPanelSpec.js
- src/test/javascript/portal/details/StylePanelSpec.js
- web-app/js/portal/details/LayerControlPanel.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/ui/openlayers/MapOptions.js
- web-app/js/portal/ui/openlayers/layer/LayerSwitcher.js
- web-app/js/portal/utils/trackUsage.js
For 
https://github.com/aodn/backlog/issues/919
Tracks data and baseLayer visibility switching
> Google Analyitics for layerSwitcher layers

- src/test/javascript/portal/search/FacetFilterPanelSpec.js
- web-app/js/portal/search/FacetDrilldownPanel.js
Fixes https://github.com/aodn/backlog/issues/5
> Fixes Backlog 5. Facets sorted Alphabetically

- grails-app/conf/Config.groovy
- web-app/js/portal/filter/ui/AlaSpeciesFilterPanel.js
- web-app/js/portal/ui/openlayers/layer/AlaWms.js
For https://github.com/aodn/backlog/issues/946
> ALA production endpoints

- src/test/javascript/portal/data/LayerStoreSpec.js
- src/test/javascript/portal/ui/MapPanelSpec.js
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/ui/MapPanel.js
- web-app/js/portal/ui/openlayers/MapOptions.js
Clear changes made to data layers and layer switcher when
"Clear and Reset" is selected on step 3.
> Fixes #2726

- test/unit/au/org/emii/portal/HostVerifierTests.groovy
Functionality was removed a while back in https://github.com/aodn/aodn-portal/pull/2687
> Remove excluded hosts tests

- web-app/js/portal/jquery.js
for those that don't fit in the available space
> Display tip for all facet names

- src/test/javascript/portal/data/LayerSelectionModelSpec.js
- src/test/javascript/portal/data/ServerSpec.js
- web-app/js/portal/data/Server.js
> JS matching knownServers done without HTTP protocol

- web-app/js/portal/data/MetadataRecord.js
So I/others don't waste time trying to work out what it is/whether its used again
> Remove unpopulated, unused field

- src/test/javascript/portal/filter/MultiStringFilterSpec.js
- web-app/js/portal/filter/MultiStringFilter.js
Fixes https://github.com/aodn/aodn-portal/issues/2755
> Fixes issue 2755

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/css/AODNTheme.css
- web-app/css/general.css
- web-app/js/portal/data/TermClassificationStore.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/search/FacetedSearchResultsPanel.js
- web-app/js/portal/service/CatalogSearcher.js
Fixes https://github.com/aodn/backlog/issues/639
> Step 1 search result terms are clickable

- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/service/CatalogSearcher.js
> More than one platform facet on step one

- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/utils/au/org/emii/portal/SilentStacktraceException.java
- src/groovy/au/org/emii/portal/wms/CoreGeoserverServer.groovy
- src/groovy/au/org/emii/portal/wms/DataTrawlerServer.groovy
- src/groovy/au/org/emii/portal/wms/FilterConfigGeoserverServer.groovy
- src/groovy/au/org/emii/portal/wms/ImosGeoserverServer.groovy
- src/groovy/au/org/emii/portal/wms/WpsUniqueValuesFilterService.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/DownloadControllerTests.groovy
- test/unit/au/org/emii/portal/wms/CoreGeoserverServerTests.groovy
- test/unit/au/org/emii/portal/wms/DataTrawlerServerTests.groovy
- test/unit/au/org/emii/portal/wms/FilterConfigGeoserverServerTests.groovy
- test/unit/au/org/emii/portal/wms/ImosGeoserverServerTests.groovy
> Quiet unit tests

- grails-app/utils/au/org/emii/portal/HttpUtils.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- web-app/js/jquery/jquery.fileDownload.js
- web-app/js/portal/cart/Downloader.js
- see comment regarding this: https://github.com/aodn/issues/issues/355
> adds cookie for detecting failed downloads

- web-app/js/jquery/jquery.fileDownload.js
- web-app/js/portal/lang/en.js
> Server timeout for downloads message updated

- web-app/js/portal/details/NcWmsPanel.js
A bit of shuffling here as the cursor style remained set to 'wait'. The request for the temporal information completes before the _filtersLoaded returns for this data collection
> Fixes #2786 when gridded data collections have no temporalExtent

- grails-app/conf/Config.groovy
for https://github.com/aodn/issues/issues/436
> biocache.ala.org.au WMS is now HTTPS

- web-app/js/portal/utils/BrowserCheck.js
Fixes https://github.com/aodn/backlog/issues/1122
> Fixed popup message for Micrsoft edge browser

- grails-app/conf/Config.groovy
> Point depth service to main Geoserver, for local dev builds

- test/unit/au/org/emii/portal/wms/CoreGeoserverServerTests.groovy
Fixes https://github.com/aodn/aodn-portal/issues/2802
> Remove test relying on external Geoserver

- src/test/javascript/portal/data/WfsDownloadHandlerSpec.js
- web-app/js/portal/cart/DownloadHandler.js
- web-app/js/portal/cart/Downloader.js
- web-app/js/portal/cart/WfsDownloadHandler.js
> Better download names for non-gridded

- grails-app/services/au/org/emii/portal/BulkDownloadService.groovy
- src/groovy/au/org/emii/portal/DownloadReport.groovy
- test/unit/au/org/emii/portal/BulkDownloadServiceTests.groovy
- test/unit/au/org/emii/portal/DownloadReportTests.groovy
For https://github.com/aodn/issues/issues/488
> report is written to a temp file as it is built instead of a big string in memory

- web-app/js/portal/cart/GaDownloadHandler.js
Fixes aodn/aodn-portal/issues/2810
> CAPTCHA response in the right place for GA

- grails-app/views/_js_includes.gsp
- pom.xml
- src/test/javascript/portal/utils/ProxySpec.js
- web-app/js/portal/utils/Proxy.js
> Clean out unused Proxy.js

- grails-app/views/_js_includes.gsp
- pom.xml
- src/test/javascript/portal/utils/ProxySpec.js
- web-app/js/portal/utils/Proxy.js
> Revert "Clean out unused Proxy.js"

- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/prototypes/OpenLayers.js
> Revert "Don't proxy WMS getURL requests"

- Jenkinsfile
#https://github.com/aodn/issues/issues/511
Requires https://github.com/aodn/jenkins-shared-library/pull/1
To be merged after all Jenkinsfiles have been updated https://github.com/aodn/cloud-deploy/pull/512
> Inject jenkins UID as BUILDER_UID

- Jenkinsfile
- bumpversion.sh
> Fix jenkins git credentials for release  (Again)

- bumpversion.sh
Forgot to include this in https://github.com/aodn/aodn-portal/pull/2823
> Remove git config from bumpversion.sh script (managed on server side)

- grails-app/conf/Config.groovy
- web-app/js/portal/data/TermClassification.js
- web-app/js/portal/prototypes/Ext.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/service/CatalogSearcher.js
https://github.com/aodn/backlog/issues/1259
> prototype portal integration with geonetwork 3 #1259

- grails-app/conf/Config.groovy
- src/groovy/au/org/emii/portal/HostVerifier.groovy
- test/unit/au/org/emii/portal/HostVerifierTests.groovy
- web-app/js/portal/data/MetadataRecord.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Implements a logo assignment mechanism that is based on the use of categories to determine which logo will be associated with a given fascet.
Backlog Issue: https://github.com/aodn/backlog/issues/1464
> Implement category based logo assignment mechanism

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/filter/FilterSpec.js
- src/test/javascript/portal/filter/SingleStringFilterSpec.js
- src/test/javascript/portal/filter/ui/GroupPanelSpec.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/SingleStringFilter.js
- web-app/js/portal/filter/ui/GroupPanel.js
Fixes https://github.com/aodn/issues/issues/661
> Reinstate single string filter

- src/groovy/au/org/emii/portal/wms/WmsServer.groovy
@jonescc you were on the money
[count=1](https://geoserver-ci-eb-geoserver-systest.aodn.org.au/geoserver/imos/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&typeName=imos%3Anoaa_drifters_map&outputFormat=json&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((58.271484375%20-29.6640625%2C58.271484375%20-7.515625%2C83.408203125%20-7.515624999999998%2C83.408203125%20-29.6640625%2C58.271484375%20-29.6640625)))&count=1)
2.3s 17Mb
[maxFeatures=1](https://geoserver-ci-eb-geoserver-systest.aodn.org.au/geoserver/imos/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&typeName=imos%3Anoaa_drifters_map&outputFormat=json&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((58.271484375%20-29.6640625%2C58.271484375%20-7.515625%2C83.408203125%20-7.515624999999998%2C83.408203125%20-29.6640625%2C58.271484375%20-29.6640625)))&maxFea …
> Limit getFeatureCount request

- grails-app/views/landing/index.gsp
> New acknowledgement statement

- .gitignore
- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/css/AODNTheme.css
- web-app/css/general.css
- web-app/js/portal/jquery.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
This better integrates the handling of long lists of organisation names with the addition of showing the abstract.
Could easily be expanded on, to show the dataset credits
Fixes https://github.com/aodn/backlog/issues/39
> fixes backlog#39

- grails-app/views/_js_includes.gsp
This has been an issue for 7 years, but until i used toggle inside the function there has been no problem in production.
> fix jquery.js included twice in production

- web-app/css/general.css
> Styling for baselayer picker

- web-app/css/AODNTheme.css
- web-app/css/general.css
Fixes aodn/aodn-portal/issues/2858
Better layout of `prev` and `next` buttons in footer
> layout prev next buttons in footer

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
Handle GN3 indexing of temporal extent
> For aodn/backlog#1822

- src/test/javascript/portal/cart/DataTrawlerDownloadHandlerSpec.js
- web-app/js/portal/cart/DataTrawlerDownloadHandler.js
https://github.com/aodn/issues/issues/779
> Fix cases where temporal and spatial extents are undefined

- grails-app/conf/Config.groovy
https://github.com/aodn/aodn-portal/issues/2874
> IMAS url update

- web-app/js/portal/cart/DownloadPanelItemTemplate.js
fixes https://github.com/aodn/aodn-portal/issues/2880
> Fixes step 3 links

- grails-app/conf/Config.groovy
Align development facets with current production facets for easier comparison
> Allow testing of AIMS collections in development

- grails-app/conf/BuildConfig.groovy
Fixes https://github.com/aodn/issues/issues/971
> Update build config to use HTTPS for Maven Central

- .bumpversion.cfg
- Dockerfile
- Jenkinsfile
- application.properties
- bumpversion.sh
- pom.xml
Aligns aodn-portal version bumping with other grails projects version bumping
> Use bump2version to bump versions, and bump via git tags

- bumpversion.sh
As per the working ones from https://github.com/aodn/backlog/issues/2616
> Fix git push command

- grails-app/conf/Config.groovy
- web-app/js/portal/cart/DownloadHandler.js
The change in Downloadhandler.js fixes the repeated menu items issue
> Add protocols for download services

- web-app/js/portal/auth/Auth.js
- web-app/js/portal/cart/Downloader.js
@nspool - I'm sure there's a easier way of doing this?
> Add user id to download

- grails-app/views/_js_includes.gsp
- grails-app/views/header/_mainPortalHeader.gsp
- grails-app/views/search/index.gsp
- scripts/CollatePortalJavaScriptSource.groovy
- web-app/js/portal/auth/Auth.js
- Remove conditional includes and hack in Collate class
- Move auth init out of _js_includes and into index.gsp
> Improve user registration feature toggle

- .bumpversion.cfg
to conform with bumpversion files in other repos
> Remove current_version from bump version file

- grails-app/views/auth/_authStatusBar.gsp
- grails-app/views/auth/_industryOptions.gsp
- grails-app/views/auth/_signInModal.gsp
- grails-app/views/auth/_signUpModal.gsp
- grails-app/views/auth/_userProfileEdit.gsp
- grails-app/views/auth/_userProfileView.gsp
- web-app/js/portal/auth/Auth.js
Change 'Industry' label to 'Institutional Type'
Change 'Sign Up' label to 'Register'
Change 'IMOS Terms & Privacy Conditions' link to point to  https://imos.org.au/imostermsofuse0
Open 'IMOS Terms & Privacy Conditions' and the 'Data Use Acknowledgement' links in new tab
Clear cookies and refresh page after sign out so that user will be prompted to sign in again
> Fix UAT UI Issues

- Dockerfile
The maven build seems to complete fine! Artifact here: https://build.aodn.org.au/job/aodn-portal_build/job/docker_ubuntu20/lastSuccessfulBuild/artifact/aodn-portal-0.0.0-production.war
> upgrade docker to latest ubuntu

- pom.xml
> Put the log4j dependency back

- grails-app/conf/Config.groovy
- src/test/javascript/portal/search/FacetDrilldownPanelSpec.js
- src/test/javascript/portal/search/FacetFilterPanelSpec.js
- src/test/javascript/portal/search/SearchFiltersPanelSpec.js
- web-app/js/portal/data/TermClassification.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/service/CatalogSearcher.js
Remove from:
aodn-portal/grails-app/conf/Config.groovy
cloud-deploy/sample-config/ebprep_conf/templates/aodn-portal/Portal.groovy.template
Used in:
TermClassification.js
FacetedSearchResultsDataView.js
CatalogSearcher.js
Also removed some failing tests
> remove gn version switching

- .run/Grails_ aodn-portal.run.xml
- web-app/js/aws-cognito/UserAuthentication.js
- web-app/js/portal/auth/Auth.js
It appears cognito may have failed to get the user for some unknown reason.
I have avoided this by getting the user from the cookie.
Also added some logging to log the error response for authenticateUser and getUserAttributes to help in future
> Get the user info from cookie and add some logging
