aodn/aodn-portal

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/ServerController.groovy
- src/test/javascript/portal/data/WfsDownloadHandlerSpec.js
- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- web-app/js/portal/cart/WfsDownloadHandler.js
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/prototypes/OpenLayers.js
This enables the possibility of using different output formats for different geoservers.
Depends on https://github.com/aodn/chef-private-sample/pull/8 and https://github.com/aodn/chef-private/pull/1348
**After** this change is deployed, then https://github.com/aodn/chef-private-sample/blob/csv_output_config/data_bags/imos_webapps_portal_known_servers/geoserver_123_aodn.json#L7 and likewise can be deleted.
> CSV output format for downloads is now configured with a string.

- src/test/javascript/OpenLayers/Layer/NcWMSSpec.js
- src/test/javascript/portal/visualise/animations/TemporalExtentSpec.js
- web-app/js/portal/ui/openlayers/layer/NcWMS.js
- web-app/js/portal/visualise/animations/TemporalExtent.js
Fixes #1603
The issue became apparent as SRS layers have many days defined (1992-2015). In particular the functions `getFirstDay()` and `getLastDay()` were scanning a big hash. They were modified to return a fixed variables which is calculated every time a new date is being added. This is addressed at a6160c7.
Another problem was the inline addition of dates. When many dates are defined this proves to be a problem. This is now done in an interleaved manner which doesn't jam the UI. This is addressed in 924a871.
Altogether the UI experience is **much** snappier now when choosing NcWMS layers and it is very apparent.
> Issue 1603

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
If a collection does not have any measured parameters, show a message indicating such, as opposed to a blank string.
> Fixes #1597.

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/domain/au/org/emii/portal/Server.groovy
- grails-app/migrations/20150310-JB-DropUrlSubstitution.groovy
- grails-app/migrations/changelog.groovy
- test/unit/au/org/emii/portal/DownloadControllerTests.groovy
- test/unit/au/org/emii/portal/LayerControllerTests.groovy
- test/unit/au/org/emii/portal/ServerControllerTests.groovy
This is a requirement for some SRS collections.
Depends on https://github.com/aodn/chef-private-sample/pull/9
> Multiple substitutions for download URLs can now be configured.

- src/test/javascript/portal/search/FacetFilterPanelSpec.js
- web-app/js/portal/search/FacetFilterPanel.js
Fixes issue #1596 
To clarify, the issue was the FilterPanel was trying to add new filters when an uncheck was occurring, even if there was no drilldown panel present (therefore causing the inconsistencies with page numbers).
> Only add new drilldown filters if the current panel has a drilldown

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- src/test/javascript/portal/filter/BoundingBoxFilterPanelSpec.js
- src/test/javascript/portal/filter/FilterGroupPanelSpec.js
- src/test/javascript/portal/filter/GeometryFilterPanelSpec.js
- src/test/javascript/portal/form/PolygonTypeComboSpec.js
- src/test/javascript/spec_helper.js
- web-app/js/portal/filter/BaseFilterPanel.js
- web-app/js/portal/filter/BooleanFilterPanel.js
- web-app/js/portal/filter/ComboFilterPanel.js
- web-app/js/portal/filter/DateFilterPanel.js
- web-app/js/portal/filter/FilterGroupPanel.js
- web-app/js/portal/filter/GeometryFilterPanel.js
- web-app/js/portal/filter/NumberFilterPanel.js
This change moves the choice of the correct UI component for a given GeoServer type to the client side. As it is it should be backwards compatible with the WFS scanner and server-side types which are used currently but which will disappear soon.
> New filter type mapping

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- web-app/js/portal/filter/FilterService.js
This is for the time being until we get filters out of the DB. At that point we can change this back to a boolean setting to choose between GeoServer (normal behaviour) and loading from filesystem (for development, troubleshooting) if needed.
> Allow filters to be loaded from DB, GeoServer, or filesystem

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/data/GeoNetworkRecordFetcherSpec.js
- src/test/javascript/portal/data/GeoNetworkRecordStoreSpec.js
- src/test/javascript/portal/data/UrlUpdaterSpec.js
- src/test/javascript/portal/ui/MainPanelSpec.js
- src/test/javascript/spec_helper.js
- web-app/js/portal/data/GeoNetworkRecordFetcher.js
- web-app/js/portal/data/GeoNetworkRecordStore.js
- web-app/js/portal/data/UrlUpdater.js
- web-app/js/portal/ui/Viewport.js
This is to make it easier for people to share links which will result in a portal with already loaded collections.
Some more 10% action - this *could* be extended further to include serialisation of filter state etc, but anyway, I think this would provide a bit of value to users.
> Updating URL when collections are added/removed.

- web-app/js/portal/form/UtcExtentDateTime.js
Ref http://www.sencha.com/forum/showthread.php?112648-OPEN-1339-Datefield-setDisabledDates-Bug-%28setting-empty-again%29
Fixes issue https://github.com/aodn/aodn-portal/issues/1644
Fixes Brewin Nanoplankton 2012 issue on production
> Do not disable dates if get missing days returns empty array, Ext bug 1339

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/MarvlController.groovy
- test/unit/au/org/emii/portal/MarvlControllerTests.groovy
This brings it in line with BODAAC.
These tests didn't fail when the BODAAC changes were made because an important function was mocked out. So I have updated the test so that changes to that function (including to it's method signature) will now break the tests.
> MARVL urlListForFeatureRequest endpoint accepts list of URL substitutions

- grails-app/controllers/au/org/emii/portal/HomeController.groovy
Hides link to empty css file when PortalBranding is not used
> fixes #1604

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- src/test/javascript/portal/filter/ComboFilterPanelSpec.js
- src/test/javascript/portal/filter/FilterServiceSpec.js
- web-app/js/portal/filter/BaseFilterPanel.js
- web-app/js/portal/filter/ComboFilterPanel.js
- web-app/js/portal/filter/EmptyFilterPanel.js
- web-app/js/portal/filter/FilterGroupPanel.js
- web-app/js/portal/filter/FilterService.js
- web-app/js/portal/lang/en.js
These changes cover three possibilities from filter loading.
1) Getting the list of filters for a layer fails - 'Filtering unavailable' message is displayed
2) Getting possible values for a filter fails - (Only currently applicable for the combo picker) drop-down is disabled with a message
3) Any filter type is unrecognised - The problem is logged but an empty UI component is used so the UI does not break
> Filters error handling

- src/test/javascript/portal/filter/BaseFilterPanelSpec.js
- web-app/js/portal/filter/BaseFilterPanel.js
- web-app/js/portal/filter/FilterService.js
This was temporary code that was in there to handle DB-configured filters alongside GeoServer/Filesystem-configured filters.
> Removed temporary code for database handling of filters

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/test/javascript/OpenLayers/Layer/NcWMSSpec.js
- test/unit/au/org/emii/portal/LayerControllerTests.groovy
- web-app/js/portal/filter/FilterService.js
- web-app/js/portal/ui/openlayers/layer/NcWMS.js
getStylesAsJSON -> getStyles
getFiltersAsJSON -> getFilters
getFilterValuesAsJSON -> getFilterValues
I don't *think* anyone will object to this change. Including 'asJSON' in the name seems redundant. Maybe it was needed as a clarification at some point.
This will break get_filters.rb eventually (when this change makes it to prod) but I think that'll be easy to pick up and fix when it happen.
> Renamed layer controller methods for filters and styles

- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- test/unit/au/org/emii/portal/wms/GeoserverServerTests.groovy
@danfruehauf a suggestion for how we can clean up the stack traces in the GeoserverServer tests.
We don't have the logging output and we don't have to add an extra code path.
> Stacktraces in logging output

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- test/unit/au/org/emii/portal/LayerControllerTests.groovy
I've accidentally committed the `dynamicFilters` setting a couple of times already today. :S
I've set it up so it can be loaded from an environment variable to make it easier when you're working from filesystem for an extended period. Default is 'false' which is to read from GeoServer.
I also took it out of the feature toggles section as per a previous discussion with @jkburges and @danfruehauf.
> Determine filter source (GeoServer/files) from env var

- grails-app/conf/Config.groovy
The 'normal' behavior will give us a FileNotFoundException
> Turn off debugging for MoTD

- get_filters.rb
- src/test/javascript/portal/common/LayerDescriptorSpec.js
- web-app/js/portal/common/LayerDescriptor.js
- web-app/js/portal/filter/FilterService.js
With this PR the Portal now loads the unique values for a filter from the map layer (instead of the data layer). The map layer should contain all the unique values represented anyway but will be much more performant.
This also fixes a bug where we were determining the download layer from the wrong field in the GeoNetwork record. It worked most of the time but failed in some cases (noticed on IMOS - Australian National Mooring Network (ANMN) Facility - Current velocity time-series).
> Unique values from WMS

- grails-app/conf/UrlMappings.groovy
I'm suggesting we remove this switch as there have now been two bugs (that I know of) which have made it to master which wouldn't have if this switch hadn't been in place. Sorry, @pmbohm, I know why we added this but I don't think it's worth the clicks it saves any more.
> Remove development mode landing page switch

- src/test/javascript/portal/filter/ui/ComboFilterPanelSpec.js
- web-app/js/portal/filter/ui/ComboFilterPanel.js
Only track events when the combo filter value has changed.
Switched to change/select events which only get generated when the component is enabled.
> Fixes #1670

- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/utils/au/org/emii/portal/HttpUtils.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- test/unit/au/org/emii/portal/DownloadControllerTests.groovy
- web-app/js/portal/cart/DownloadPanelBody.js
- web-app/js/portal/lang/en.js
Decision to use ext.alert was done in consultation with @pblain. 
Fixes issue #1623. 
This PR introduces error messaging to the the user on the client side. Currently handles disallowed geoserver urls (without any necessary changes to the server side after https://github.com/aodn/aodn-portal/pull/1684), and will be expanded on for my fix for #1624
> alert user to unsuccessful download caused by disallowed geoserver

- src/test/javascript/portal/data/BodaacDownloadHandlerSpec.js
- web-app/js/portal/filter/combiner/BaseFilterCombiner.js
- web-app/js/portal/filter/combiner/BodaacCqlBuilder.js
- web-app/js/portal/filter/combiner/DataDownloadCqlBuilder.js
- web-app/js/portal/filter/combiner/HumanReadableFilterDescriber.js
- web-app/js/portal/filter/combiner/MapCqlBuilder.js
This replaces a couple of custom functions I'd written because I couldn't find the behaviour that I wanted (I was looking in Ext docs not thinking that they might be pure JS).
`_matchingFilters(array, fn)` is replaced with `array.filter(fn)` (Unfortunately, this name is confusing given that I am using it in the code for the Portal filters)
`_collect(array, fn)` is replaced with `array.map(fn)`
> Remove redundant functions

- src/test/javascript/portal/cart/WmsInjectorSpec.js
- src/test/javascript/portal/data/BodaacDownloadHandlerSpec.js
- web-app/js/portal/filter/combiner/BaseFilterCombiner.js
My recent changes in 12112494ccd99db9c5db113e045d3f92c734c60e and 142a278872f1be59a604bdcdf0c6307ac7e191d1 meant that they are no longer null-safe. I updated tests so they'd work but it turns out this also happens during normal operation so instead I'll substitute in an empty array if filters are undefined.
> Proper handling of undefined filters

- src/test/javascript/portal/cart/NcwmsInjectorSpec.js
- src/test/javascript/portal/filter/BooleanFilterSpec.js
- src/test/javascript/portal/filter/DateFilterSpec.js
- src/test/javascript/portal/filter/GeometryFilterSpec.js
- src/test/javascript/portal/filter/NumberFilterSpec.js
- src/test/javascript/portal/filter/StringFilterSpec.js
- src/test/javascript/portal/filter/ui/NumberFilterPanelSpec.js
- web-app/js/portal/cart/NcwmsInjector.js
- web-app/js/portal/filter/BooleanFilter.js
- web-app/js/portal/filter/DateFilter.js
- web-app/js/portal/filter/GeometryFilter.js
- web-app/js/portal/filter/NumberFilter.js
- web-app/js/portal/filter/StringFilter.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
- web-app/js/portal/lang/en.js
This is a tidy-up of filters display in step 3.  It stems from #1626 but goes a lot further.
The main changes are:
- On step 3 all filters are displayed as `label: value`. (There was inconsistency with this.)
- The labels for spatial and temporal extent are now consistent between step 2 and step 3. (Previously they weren't).
- Regarding displaying of filter values on step 3 there was a mix of word-type display and raw CQL. This has now been made more consistent.
- There was inconsistency with labelling between ncWMS spatial filters and WMS spatial filters
- There was inconsistency with labelling between ncWMS temporal filters and WMS temporal filters
- Moved some text to the i18n dictionary
- Added a tooltip to symbols in the number filter so you can see in words what the symbol means
> Step 3 filter tidy (#1626)

- src/test/javascript/portal/filter/FilterServiceSpec.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/FilterService.js
- web-app/js/portal/filter/ui/BaseFilterPanel.js
- web-app/js/portal/filter/ui/ComboFilterPanel.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
This addresses issue #1675
It introduces a new concept of a primary filter. This is based on some upcoming work where the geographic filter will be above and outside all layers (aka accordion) as will the temporal extent. However, we support more than one temporal extent so when that work happens we'll need a way to determine which is the primary temporal filter (which should therefore go outside the normal list of filters). For now a time filter is the primary if it is the only one for that layer. I'm happy to talk about this if my idea needs clarification.
> Issue #1675

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/js/portal/filter/Filter.js
This is left over from the filters prototype. Things have changed in such a way that this function isn't used anymore.
> Remove unused Filter getType() function

- web-app/js/portal/filter/ui/NumberFilterPanel.js
This should have been part of 6328f509cfb2532a16c3481fd3f683ec507e1afb. This code is replaced with this line https://github.com/aodn/aodn-portal/blob/0b3e2aaf46e48a0e7e8471f5080fea3c69e22017/web-app/js/portal/filter/ui/NumberFilterPanel.js#L30
> Remove usage of undefined variable

- src/test/javascript/portal/cart/DownloadPanelSpec.js
- src/test/javascript/portal/data/ActiveGeoNetworkRecordStoreSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- src/test/javascript/portal/filter/ui/GeometryFilterPanelSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsMiniMapSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsPanelSpec.js
- src/test/javascript/portal/ui/DownloadCartWidgetSpec.js
- src/test/javascript/portal/ui/MainPanelSpec.js
- src/test/javascript/portal/ui/MapPanelSpec.js
- src/test/javascript/portal/ui/VisualisePanelSpec.js
- web-app/css/general.css
- web-app/js/portal/PortalEvents.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/data/ActiveGeoNetworkRecordStore.js
- web-app/js/portal/data/GeoNetworkRecordFetcher.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/details/SpatialSubsetControlsPanel.js
- web-app/js/portal/details/SubsetPanel.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/filter/ui/GeometryFilterPanel.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
- web-app/js/portal/search/FacetedSearchResultsPanel.js
- web-app/js/portal/ui/DownloadCartWidget.js
- web-app/js/portal/ui/MainPanel.js
- web-app/js/portal/ui/MapPanel.js
- web-app/js/portal/ui/VisualisePanel.js
This is a little something that I think will be handy. It lets you ctrl+click on step 1 and add multiple collections without being taken to step 2 for each one.
Current bugs:
* There is a problem with map binding to a few UI controls (to reproduce just ctrl+click before you've added any other data collections)
Nice to have:
* There are a few page elements that move about when you ctrl+click add a data collection (mainly the mini-map, I think). It would be nice if they didn't move when you added collections (and just greyed-out).
> Add multiple collections with ctrl+click

- src/test/javascript/portal/filter/ui/NumberFilterPanelSpec.js
- web-app/js/portal/filter/ui/NumberFilterPanel.js
Fixes the possibility of invalid CQL causing the portal to mark the layer invalid when using the 'between' filter and leaving either the first or second field empty.
> fixes #1696

- src/test/javascript/portal/cart/DownloadPanelSpec.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/utils/trackUsage.js
Request by @pblain.
The main difference is that we will have the aggregation parameters - and we can actually understand what people are doing with GGD.
> track gogoduck downloads with GA

- src/test/javascript/portal/cart/DownloaderSpec.js
- web-app/js/portal/cart/Downloader.js
do not post unnecessary parameters for GGD jobs
It can probably be refactored to look a bit nicer, such as binding the success function with the correct parameters, however I'm not too fussed about it.
> do not post unnecessary parameters for GGD jobs

- src/test/javascript/portal/cart/DownloaderSpec.js
- web-app/js/portal/cart/Downloader.js
not binding params to `this` anymore. it does make the testing a bit
uglier, but the code cleaner.
> refactor Downlader call to GGD

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- grails-app/utils/au/org/emii/portal/HtmlCharacterEntityReferences.groovy
- grails-app/utils/au/org/emii/portal/HtmlUtils.groovy
Fixes issue #1748 in conjunction with chef upgrade
> Determine character encoding of metadata xml stream before escaping

- src/test/javascript/portal/filter/NumberFilterSpec.js
- web-app/js/portal/filter/NumberFilter.js
Fixes #1787
Also, we no longer check whether the second field has a value as there isn't a case where it should have a value without the first field also having a value.
> Number filter hasValue should return true if comparison value is 0

- web-app/css/general.css
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/lang/en.js
- web-app/js/portal/search/DateSelectionPanel.js
- web-app/js/portal/search/FacetFilterPanel.js
- web-app/js/portal/search/GeoSelectionPanel.js
Toolbar items using FontAwesome. The step 1 add extra criteria button is now only visible when available instead of being disabled. It was hard to tell when the extra criteria button were active or disabled as there are no expand/collapse icons anymore on step1, which matches Step2
> Fixes #1793 and fixes #1792

- src/test/javascript/portal/data/LayerStoreSpec.js
- src/test/javascript/portal/ui/MapPanelSpec.js
- web-app/js/portal/data/ActiveGeoNetworkRecordStore.js
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/details/SubsetPanelAccordion.js
- web-app/js/portal/details/SubsettingPanel.js
- web-app/js/portal/ui/MapPanel.js
This change removes data collection reordering from the Portal. It also changes the behaviour such that the currently-selected layer is always on the top of the map view. This means that the layer you're subsetting is never obscured by another layer.
> Selected layer always on top on map

- web-app/js/portal/details/SubsetPanelAccordion.js
- web-app/js/portal/prototypes/NonCollapsingAccordionLayout.js
This fixes a bug that @pmbohm spotted where Ext has trouble with names that aren't all lowercase.
> NonCollapsingAccordionLayout component name

- web-app/js/portal/details/SubsettingPanel.js
- web-app/js/portal/prototypes/NonCollapsingAccordionLayout.js
Now publishes 'PORTAL_EVENTS.SELECTED_LAYER_CHANGED' when an accordion item is expanded, therefore the map is notified
> fixes #1821 - without creating new bugs!

- grails-app/views/header/_mainPortalHeader.gsp
Had to do this manually, rather than git-revert.  See
aodn/aodn-portal#1847.
Will need a corresponding change to the chef recipe if generating the
config file that way.
> Revert 44895d2eb; make help links configurable

- src/test/javascript/portal/search/FacetedSearchResultsPanelSpec.js
- src/test/javascript/portal/search/SearchBodyPanelSpec.js
- web-app/js/portal/search/FacetedSearchResultsPanel.js
- web-app/js/portal/search/SearchBodyPanel.js
the bug stems from scrolling the wrong element on store reloads,
this commit fixes it by scrolling searchResultsPanel, which is the
element with the scroll bar, rather than scrolling
FacetedSearchResultsPanel, which is just the encapsulated element
fixes #1834
> fix #1834, scroll to top search results

- src/test/javascript/portal/ui/MapPanelSpec.js
mock OpenLayers.Util.getImageLocation
fixes #1851
> avoid failing network requests while running tests

- grails-app/taglib/au/org/emii/portal/MessageOfTheDayTagLib.groovy
- src/groovy/au/org/emii/portal/PortalBranding.groovy
- test/unit/au/org/emii/portal/PortalBrandingTests.groovy
if brandingBase is defined, motd is being taken from
brandingBase/motd. makes it easier to reuse the motd functionality
after rebranding the portal
requested originally by @markhepburn
> motd used from brandingBase

- grails-app/conf/Config.groovy
I think we can get away without this comment. It has already gotten out-of-date
(as many comments do) and essentially all of the information can be found from
the usages that follow it.
> Remove comment describing knownServers config structure

- src/test/javascript/portal/cart/InsertionServiceSpec.js
- src/test/javascript/portal/data/BodaacDownloadHandlerSpec.js
- src/test/javascript/portal/data/DataCollectionLayersSpec.js
- src/test/javascript/portal/data/DataCollectionSpec.js
- src/test/javascript/portal/data/WfsDownloadHandlerSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- src/test/javascript/portal/details/StylePanelSpec.js
- src/test/javascript/portal/details/SubsetItemsWrapperPanelSpec.js
- src/test/javascript/portal/details/SubsetPanelSpec.js
- src/test/javascript/portal/filter/FilterServiceSpec.js
- src/test/javascript/portal/filter/ui/BooleanFilterPanelSpec.js
- src/test/javascript/portal/filter/ui/ComboFilterPanelSpec.js
- src/test/javascript/portal/filter/ui/DateFilterPanelSpec.js
- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- src/test/javascript/portal/filter/ui/NumberFilterPanelSpec.js
- web-app/js/portal/cart/BodaacDownloadHandler.js
- web-app/js/portal/cart/InsertionService.js
- web-app/js/portal/cart/PythonDownloadHandler.js
- web-app/js/portal/cart/WfsDownloadHandler.js
- web-app/js/portal/data/DataCollection.js
- web-app/js/portal/data/DataCollectionLayers.js
- web-app/js/portal/data/DataCollectionStore.js
- web-app/js/portal/details/LayerDetailsPanel.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/details/SubsetItemsTabPanel.js
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/details/SubsetPanel.js
- web-app/js/portal/filter/FilterService.js
* remove `DataCollection.getSelectedLayer()` - this must now be accessed via the `DataCollectionLayers` object.
I am now looking to:
1. remove unnecessary access to the `DataCollectionLayers` object
1. rename the class to something better (`LayerList` is the leading candidate currently)
1) above will hopefully allow me to delete much of the mocking present in this PR.
> Data Collection Layers refactor

- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
- web-app/js/portal/filter/ui/GeometryFilterService.js
Simplify _clearFilters() in FilterGroupPanel. handleRemoveFilter() should always be safe to call so there is no need to prevent it from being called on a Geometry filter.
> Simplify filter clearing logic

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/data/DataCollectionStoreSpec.js
- src/test/javascript/portal/data/LayerStoreSpec.js
- src/test/javascript/portal/details/NcwmsScaleRangeControlsSpec.js
- src/test/javascript/portal/details/StylePanelSpec.js
- src/test/javascript/portal/details/SubsetItemsWrapperPanelSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsMiniMapSpec.js
- src/test/javascript/portal/ui/MapPanelSpec.js
- src/test/javascript/portal/ui/ViewportSpec.js
- src/test/javascript/spec_helper.js
- web-app/js/portal/PortalEvents.js
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/details/NcwmsScaleRangeControls.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/details/SubsetPanelAccordion.js
- web-app/js/portal/search/FacetMapPanel.js
- web-app/js/portal/search/FacetedSearchResultsMiniMap.js
- web-app/js/portal/ui/MapPanel.js
- web-app/js/portal/ui/Viewport.js
- web-app/js/portal/ui/openlayers/layer/MiniMapBaseLayer.js
Removed global `SELECTED_LAYER_CHANGED` event, preferring to use `DATA_COLLECTION_SELECTED`, or `DataCollection` scoped `selectedlayerchange` event, where appropriate.
This is a step towards making the portal "data collection centric" (rather than layer centric, as was the case previously).
> Selected layer changed event

- web-app/js/portal/details/SubsetItemsTabPanel.js
This was also a leftover usage of ths.layer which was no longer needed.
> Remove unused GoogleAnalytics tracking code

- src/test/javascript/portal/cart/DownloadPanelSpec.js
- src/test/javascript/portal/data/BodaacDownloadHandlerSpec.js
- src/test/javascript/portal/data/DataCollectionLayersSpec.js
- src/test/javascript/portal/data/WfsDownloadHandlerSpec.js
- src/test/javascript/portal/details/SubsetItemsWrapperPanelSpec.js
- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- web-app/js/portal/cart/BodaacDownloadHandler.js
- web-app/js/portal/cart/PythonDownloadHandler.js
- web-app/js/portal/cart/WfsDownloadHandler.js
- web-app/js/portal/data/DataCollectionLayers.js
- web-app/js/portal/details/SubsetItemsWrapperPanel.js
- web-app/js/portal/prototypes/OpenLayers.js
It's preferable for components to be driven off DataCollection and only off selected layer where absolutely necessary.
> Remove dependency on `getSelectedLayer()` where possible

- src/test/javascript/portal/cart/GogoduckDownloadHandlerSpec.js
- src/test/javascript/portal/cart/NcWmsInjectorSpec.js
- src/test/javascript/portal/data/DataCollectionSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/NcWmsInjector.js
- web-app/js/portal/data/DataCollection.js
- web-app/js/portal/details/NcWmsPanel.js
We have removed references to ncwmsParams from DataCollection. We now
convert ncwmsParams into a list of filters and store them as such.
Then when they are used (2 places) we decode them back into ncwmsParams.
These conversion steps will be eliminated when
https://github.com/aodn/backlog/issues/191 is completed.
> Remove knowledge of ncwmsParams from DataCollection

- web-app/js/portal/prototypes/NonCollapsingAccordionLayout.js
Increasing the timeout on requesting collapse for panels which should be closed but still have the property collapsed set to true as the Ext expand animation still executes.
Tested on my own machine and demonstrated the bug with a timeout of 400ms. 
800ms seems to fix the bug without any adverse side affects at the moment. There may be times when this isn't enough, but given the now fairly extreme measures required to create the bug I think we could stop here?
Fixes #1823
> lengthen timeout for collapsing panels- accordion layout

- pom.xml
This reverts commit 8abd85b65a7ced410d96e1e0745ad4564b55c5cd.
Phantomjs is intermittently hanging.
e.g.: https://travis-ci.org/aodn/aodn-portal/builds/77274087
So, we go back to html unit for now.
There's some discussion about this problem on phantomjs github issues, but no resolution.
> Revert "Use phantomjs to execute tests"

- grails-app/conf/Config.groovy
- src/test/javascript/portal/cart/BaseInjectorSpec.js
- src/test/javascript/portal/cart/NoDataInjectorSpec.js
- src/test/javascript/portal/data/DataCollectionSpec.js
- src/test/javascript/portal/data/LayerSelectionModelSpec.js
- src/test/javascript/portal/details/InfoPanelSpec.js
- web-app/js/portal/cart/BaseInjector.js
- web-app/js/portal/data/DataCollection.js
- web-app/js/portal/data/LayerSelectionModel.js
- web-app/js/portal/details/InfoPanel.js
This removes the individual get______Links() methods from DataCollection and has just one method getLinksByProtocol() which you can pass the protocols you are interested in. This new function is also used for getting the point-of-truth link from a DataCollection.
> Remove get_____Links from DataCollection

- grails-app/conf/Config.groovy
- src/test/javascript/portal/common/LayerDescriptorSpec.js
- src/test/javascript/portal/details/LayerControlPanelSpec.js
- src/test/javascript/portal/ui/MapPanelSpec.js
- web-app/js/portal/common/LayerDescriptor.js
- web-app/js/portal/data/DataCollectionLayerAdapter.js
- web-app/js/portal/details/LayerControlPanel.js
- web-app/js/portal/ui/MapPanel.js
- web-app/js/portal/ui/openlayers/MapOptions.js
Bounds are taken directly from the data collection, rather than storing in each layer and then taking from there - that's just a round-a-bout and unnecessary way of doing it now that most components are 'data collection centric'.
This also addresses a usability issue whereby the 'zoom to layer' control is only shown for collections having a geo extent defined.  Ordinarily this should be the case for *every* collection, although this is the safer option and can probably also help avoid confusion when developing new collections.  /cc @kereid @pblain change to functionality
> Clean up of zoom to layer

- src/test/javascript/portal/ui/openlayers/control/SpatialConstraintSpec.js
mock calls to spatialConstraint._resetSpatialExtentError
> fix #1929 - avoid js unit test exceptions

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- src/test/javascript/portal/details/InfoPanelSpec.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/details/InfoPanel.js
parse correct links from metadata for step 2 and 3
an easy fix for a pretty critical issue (most links displayed are actually broken!!)
> fix #1940 - bogus link parsing

- web-app/js/portal/details/NcWmsPanel.js
The values applied to the collections temporal filter were not set until the times in a day were retrieved.
The Download Panel is not aware of the event of the days extent loading having completed, and so was never updated
> Fixes #1922

- grails-app/views/header/_viewPortLink.gsp
- web-app/css/general.css
- web-app/js/portal/jquery.js
Stops the issue of appended hashes appearing on the Step1-2-3 links by using button tags instead of links.
See:
https://github.com/aodn/aodn-portal/issues/1958
> Avoid generating URLs with hashes

- src/test/javascript/portal/common/LayerDescriptorSpec.js
- src/test/javascript/portal/data/ServerSpec.js
- web-app/js/portal/common/LayerDescriptor.js
- web-app/js/portal/data/Server.js
This PR has some changes which I made yesterday when working with Ming (@fxmzb123) to get the TPAC layers working in the Portal. They are served from THREDDS-embedded ncWMS. The problem was that there is an extra dataset name after the base URL. So for example, if we used the THREDDS ncWMS, we'd have something like this:
http://thredds.aodn.org.au/wms/abos
http://thredds.aodn.org.au/wms/anmn
http://thredds.aodn.org.au/wms/agro
... etc.
So to make it work we could have added a known server for every dataset (which would be ugly and brittle), or we could change the code so that a configured server with 'http://thredds.aodn.org.au/wms' would match any dataset that it serves.
There are two changes in this PR.
1. Changing known Server comparison method
Previously we compared the server URL …
> Server check changes

- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/services/au/org/emii/portal/GogoduckService.groovy
- grails-app/services/au/org/emii/portal/WpsService.groovy
- grails-app/views/wps/_asyncRequest.xml.gsp
- src/groovy/au/org/emii/portal/AsyncDownloadService.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/AsyncDownloadServiceTests.groovy
- test/unit/au/org/emii/portal/GogoduckServiceTests.groovy
- test/unit/au/org/emii/portal/WpsServiceTests.groovy
This PR makes it possible for the portal to send WPS requests to a WPS enabled geoserver, with a request such as the following:
```
curl "http://localhost:8080/aodn-portal/asyncDownload?aggregatorService=wps&jobParams.namespace=imos&jobParams.typeName=anmn_ts_timeseries_data&jobParams.cqlFilter=INTERSECTS(geom%2CPOLYGON((113.33%20-34.09%2C113.33%20-30.98%2C131.11%20-30.98%2C131.11%20-34.09%2C113.33%20-34.09)))%20AND%20TIME%20%26gt%3B%3D%20%272009-01-13T23%3A00%3A00Z%27%20AND%20TIME%20%26lt%3B%3D%20%272009-02-01T00%3A00%3A00Z%27&server=http://geoserver-systest.aodn.org.au/geoserver/wps"
```
Note: this request format has changed slightly due to c4d92003886cbc -  specifically the extra level of hierarchy in the request `jobParams`.
> Wps service

- src/test/javascript/portal/service/CatalogSearcherSpec.js
- web-app/js/portal/service/CatalogSearcher.js
* Do not pass any `filters=` values by default, for backward
compatibility
* Pass `filters=collectionavaiability` if passed `healthy=true`
this will show all healthy layers
* Pass `filters=!collectionavaiability` if passed `healthy=false`
this will show all broken layers
> Support collection availability in Geonetwork

- web-app/js/portal/filter/ui/FilterGroupPanel.js
FilterGroupPanel has height 'auto' to avoid excess spacing at the bottom.
> Fix for #1985

- src/test/javascript/portal/data/DataCollectionSpec.js
- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/data/DataCollection.js
[![Alt text for your video](http://img.youtube.com/vi/n1EymCZSqFg/0.jpg)](http://www.youtube.com/watch?v=n1EymCZSqFg)
Don't attempt to load filters from the server for NcWms - currently, they are hard-coded in the client and trying to load from server just wipes out the desired filters with an empty list.  This in turn causes problems such as #1999.
Note that the proper fix is to treat NcWms collections like any other, i.e.:
* load filters from server
* model filters in exactly the same way as non-ncwms
* use the same UI components as non-ncwms
This can be reverted when *all* collections, [NcWms and non-NcWms, are treated the same as far as filtering is concerned](https://github.com/aodn/backlog/issues/191).
> Fixes #1999

- src/test/javascript/portal/cart/NcWmsInjectorSpec.js
- web-app/js/portal/cart/NcWmsInjector.js
The test for whether a spatial extent is enterred used truthiness and therefor
a value of 0 was considered false (e.g. not set). By checking against undefined
we allow people to enter a latitude of 0.
> Fixes #2019

- src/test/javascript/portal/ui/openlayers/layer/NcWmsSpec.js
- web-app/js/portal/ui/openlayers/layer/NcWms.js
* Add Z when requesting time to denote UTC (thredds need that)
* Pass service=ncwms, so Geoserver uses ncwms plugin instead of
the default wms plugin. Doesn't affect regular ncwms
interaction
> Tiny modifications required to work with ncwms plugin

- src/groovy/au/org/emii/portal/wms/NcwmsServer.groovy
- web-app/js/portal/ui/openlayers/layer/NcWms.js
Ncwms layer name will look like `workspace:layer#time,file_url/variable`.
This introduces the `#`, which will allow users to control from
metadata which `time` and `file_url` columns names they would
like to use when using the abomination ncwms controller.
After introducing the `#`, it means we need to encode the layer
name properly in JS land. The server side changes ensure that
when accessing geoserver backends (ncwms abomination controller),
the layer name will be encoded.
This does not affect regular ncwms layers where the layer does not
need to be encoded.
> Encode ncwms layer name

- web-app/js/portal/details/StylePanel.js
Amend 41b46c4, also GetLegendGraphic needs to encode the layer as
it will contain `#`s.
> URL encode layer in GetLegendGraphic

- src/test/javascript/portal/ui/FeatureInfoPopupSpec.js
- web-app/js/portal/ui/FeatureInfoPopup.js
By itself this does not solve the issue that the GFI requests dont seem to return hits often enough. It does solve the issue where requests returned server errors as the value for the 'X' click point became a negative number and this always failed. Possibly upgrades to Geoserver and or Openlayers produced this outcome?
The error can be seen by adding the code below to the `findFeatures` function in `FeatureInfoPopup.js`. Whenever x is negative there will have been a 500 error returned. _Click on the right of the map_
```
console.log(event.xy);
this.loc = this.map.getLonLatFromViewPortPx(event.xy);
var pix = this.map.getViewPortPxFromLonLat(this.loc);
console.log(this.loc);
console.log("x: " + pix.x );
```
This bug also comes from styling issues where lines are styled too small for the …
> Send correct click point values to GFI requests

- grails-app/controllers/au/org/emii/portal/WpsController.groovy
- src/groovy/au/org/emii/portal/proxying/HostVerifyingController.groovy
- src/groovy/au/org/emii/portal/proxying/RequestProxyingController.groovy
- test/unit/au/org/emii/portal/WpsControllerTests.groovy
- test/unit/au/org/emii/portal/proxying/HostVerifyingControllerTests.groovy
The WPS controller previously extended from RequestProxyingController to get the known servers URL verification for free. However, it was a bit messy because we were overwriting internal logic because it isn't really proxying requests for the Portal client. So I extracted the host-validation logic into a new controller so that controllers can just subclass that for the behaviour.
So instead of (mis)using `_performProxyingIfAllowed()` we can just use the new method `_ifAllowed(url)`.
> Controller improvements

- src/test/javascript/portal/cart/DownloaderSpec.js
- web-app/css/imosTheme.css
- web-app/js/portal/cart/Downloader.js
- web-app/js/portal/lang/en.js
Opens an Ext popup as soon as the user clicks the button to request a WPS download. This informs the user s that something happened. When the job is successfully registered (or failed) the same popup will be used.
Although Ext does a nice job of closing old popups for us, it is probably fractionally speedier to reuse the same this.messageBox. It also keeps the same width.
> WPS downloads now have a popup as soon as job requested

- src/test/javascript/portal/search/FacetedSearchResultsMiniMapSpec.js
- web-app/js/portal/search/FacetedSearchResultsMiniMap.js
Essentially the the bug is that the whole extent of the collection should now show for all collections. Still reliant on Openlayers to do the best fit
Fixes #2048
> Minimaps use zoomToExtent function now

- grails-app/conf/Config.groovy
- src/groovy/au/org/emii/portal/HostVerifier.groovy
If `config.allowAnyHost` is set to true, bypass HostVerifier and allow
interaction with any backend host.
> Allow bypassing HostVerifier

- web-app/js/portal/search/FacetedSearchResultsDataView.js
`max-height` is a bit too new for most browsers, but will override, when present, the old school `height` attribute now added by this pull request
> Fixes #2107

- web-app/js/portal/search/GeoSelectionPanel.js
Let the browser not EXT position the controls, complementing the CSS rules which are overlaying the controls over the map
> Fixes #2121

- src/test/javascript/portal/cart/DownloadConfirmationWindowSpec.js
- web-app/js/portal/cart/DownloadConfirmationWindow.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/data/MetadataRecord.js
- web-app/js/portal/lang/en.js
There's a few dependencies involved before this can be usefully deployed:
* A bugfix on the otherConstraints indexing (aodn/schema-plugins#30)
* Inclusion of the licence image link in indexing (aodn/schema-plugins#31)
* dump both the otherConstraints and image link fields in geonetwork (aodn/core-geonetwork#58)
Otherwise though, it's essentially just a matter of formatting.  Since there are repeated and optional fields, I've switched to using a Extjs template instead of OL templates.
> Citation Feature: populate download confirmation from metadata record

- src/test/javascript/portal/cart/NetcdfSubsetServiceDownloadHandlerSpec.js
- web-app/js/portal/cart/NetcdfSubsetServiceDownloadHandler.js
The nominated measurement timestamp property should be used for temporal filtering not the temporal coverage start and end timestamps used for filtering the WMS layer.
There is also an issue with the conversion of the date selected in the temporal filters to UTC which will be addressed separately (converted from a local date/time to UTC which is unexpected)
> Partial fix for #2134

- src/test/javascript/portal/utils/TimeUtilSpec.js
- web-app/js/portal/filter/DateFilter.js
- web-app/js/portal/utils/TimeUtil.js
When testing https://github.com/aodn/aodn-portal/pull/2141 for https://github.com/aodn/aodn-portal/issues/2134, I noticed that dates selected in the date filter for non-gridded data are treated as being in local time and converted to UTC before being sent geoserver for subsetting (WFS and WPS).
So 2013/3/26 would be converted to UTC and sent to Geoserver as 2013-03-25T13:00:00Z resulting in my Netcdf files (or CSV files) including data from this timestamp onwards.
Date/Times selected for gridded data are treated as being at UTC and so the treatment of date/times is inconsistent between gridded and non-gridded data.
This PR makes the treatment of the date selected for non-gridded data consistent with that of gridded data.  It also makes it work the way I was expecting - i.e. I selected …
> Don't convert date filter from local time to UTC

- src/test/javascript/portal/cart/DownloadPanelSpec.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/GogoduckDownloadHandler.js
- web-app/js/portal/cart/GogoduckV1DownloadHandler.js
- web-app/js/portal/cart/NetcdfSubsetServiceDownloadHandler.js
- web-app/js/portal/filter/DateFilter.js
@jonescc Track download changes now in one place with the filters supplied as human readable text as the data
> Fixes #2132 trackDownloadUsage is only done on accepting license dialog box.

- src/test/javascript/portal/cart/DownloadPanelItemTemplateSpec.js
- web-app/css/AODNTheme.css
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/details/DataCollectionDetailsPanel.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
part fixes https://github.com/aodn/backlog/issues/361
> Titles are now trimmed when excessively long. Hover shows full title with default cursor

- web-app/js/portal/ui/FeatureInfoPopup.js
Units will not be stated if the metadata does not contain units.
Related work to correctly return units comes from https://github.com/aodn/geoserver-build/pull/138
> Fixes 2188 - unit information comes from metadata only

- grails-app/controllers/au/org/emii/portal/ExternalConfigReloadController.groovy
This enables the external groovy config file(s) to be reloaded without restarting Tomcat.
Currently if Portal.groovy (or any other hypothetical external config file) is updated but the WAR contents are not, the new configuration will not be effective until Tomcat is restarted.
Example usage: (from localhost *only*): 
```bash
[/var/log/tomcat8]# wget -q http://localhost:8080/ExternalConfigReload -O/dev/null
[/var/log/tomcat8]# tail catalina.out 
13-Sep-2016 05:54:00.447 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Sep-2016 05:54:00.463 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
13-Sep-2016 05:54:00.467 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 18839 ms …
```
> Add simple controller to trigger reload of external config files

- web-app/js/portal/ui/openlayers/control/SpatialConstraint.js
> Set correct scope for timeout to redraw previous spatial extent on error

- src/test/javascript/portal/filter/ui/DateFilterPanelSpec.js
- web-app/js/portal/filter/ui/DateFilterPanel.js
- web-app/js/portal/filter/ui/ResettableDate.js
Fixes issue #2317.
I've renamed a few functions to avoid confusion.
Allow blank fields as this defaults to min and max of the spatial extent for collection.
> Validate from and to date fields on value change after updating minmax

- src/test/javascript/portal/cart/NcWmsInjectorSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/PortalEvents.js
- web-app/js/portal/cart/DownloadPanel.js
- web-app/js/portal/cart/DownloadPanelItemTemplate.js
- web-app/js/portal/cart/NcWmsInjector.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/lang/en.js
When a user loads a ncWMS layer and goes quickly to step 3, the page indicate that the Temporal extent filters are loading, and the download options are disabled during this time. This happens even on fast internet connections such as UTAS.
- Now the download panel (step 3) will reload when temporal filters finish loading, in this way the temporal filter should be correct before the user can choose a download option if the download option button is enabled that is.
- The user will see a message when the temporal extent matches the full extent of the chosen layer of the collection. This message is advisory and the download button is enabled
> Issue 2395

- selenium/src/test/java/au/org/emii/portal/tests/step1/PaginateInResults.java
The paginate forward test already tested the 'first page' button, needed to add a test for the 'previous' button and rename to acknowledge that it doesn't just test forward pagination.
https://aodn.testrail.com/index.php?/cases/view/16&group_by=cases:section_id&group_order=asc&group_id=4
> Test 'previous' button as well

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/SearchController.groovy
Related to #2423 which was working on localhost but not on edge and systest because of a  difference between serverurls having or not having a backslash at the end
> Fixes sitemap for non-development environments

- grails-app/views/robots.gsp
The sitemap had the XML extension instead of TXT
> Sitemap Url as text file

- web-app/js/portal/prototypes/OpenLayers.js
(required change for geowebcache comparability)
> Get rid of unneeded spaces in EPSG parameters of getfeatureinfo requests

- web-app/js/portal/jquery.js
Some events weren't being run due to JQuery3 handling events differently.
JQuery3 Upgrade (see #2458) predictably caused a bunch of issues:
- Mouse over title text on the last level facet menu items wasn't working
- Mouse over title text on "pin" icon of getfeatureinfo wasn't working
- FeatureInfo hyperlink clicks were not being tracked
- Search results which were too long to fit in regular size couldn't be expanded
There were two events being added in jquery.js (lines 32 and 65 of the unrefactored file) which I couldn't for the life of me work out what they were supposed to do. I therefore removed them as a I strongly suspect they're remnants of long deceased features.
> Fixed various issues introduced by JQuery upgrade.

- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- web-app/js/portal/prototypes/OpenLayers.js
Use BBOX ordering correctly for wmsVersion regardless of isNcwms
> Fixes #2461

- web-app/js/portal/search/FacetedSearchResultsDataView.js
Fixes the console red. Thanks for providing the fix @julian1 
@jonescc Is this still the best way to update the Geonetwork popularity?
This URL now returns about a thousand lines of unused response
> Fixes #2478 Update Geonetwork URL called to update popularity

- web-app/js/portal/jquery.js
When expanding a result, only set the originalheight when it is not already defined, meaning only on the first run. The original height should never change so this is cleaner than what we had before even if it doesn't fix the bug.
> Possibly fixes #2507

- src/groovy/au/org/emii/portal/wms/GeoserverServer.groovy
- test/unit/au/org/emii/portal/wms/GeoserverServerTests.groovy
for enabledFilters and uniqueValues requests
> Send workspace and layername together rather than as separate parameters

- selenium/src/test/java/au/org/emii/portal/tests/step1/ExpandCollapseLargeRecordTest.java
- selenium/src/test/java/au/org/emii/portal/utils/WebElementUtil.java
- web-app/js/portal/jquery.js
The refactoring ensures we are definitely testing the correct elements should the order have been a problem.
I noticed the tests were always succeeding when i had lots of debug lines and queries within the test. This suggests that although we are waiting for animations to end, the style attributes were still not written into the page and we were testing them too early, hence the new wait.
> Reworking of the test.

- application.properties
- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/services/au/org/emii/portal/WpsAwsService.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/WpsAwsServiceTests.groovy
Required for the new AWS batch GoGoDuck. Will break status urls returned from Geoserver GoGoDuck
> Status urls from Batch/Geoserver GoGoDuck in popup

- web-app/css/general.css
This was affecting Deakin who have their portal with the context set as `/portal`
The problem can be seen on http://po.aodn.org.au/imos123/search
This fix works with contextless setups like production or through intellij
> Fix #2574 absolute image path GFI popup pointers

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- src/groovy/au/org/emii/portal/HostVerifier.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
- test/unit/au/org/emii/portal/HostVerifierTests.groovy
Blacklist prod wps endpoints in development and verify WPS requests in any environment are to an allowed host before submitting them.
> Stop developers submitting requests to prod WPS

- selenium/src/test/resources/testng.xml
Fixes #2545 and #2554.
Firefox started using a completely new driver in version 48.0 and that driver doesn't fully support the WebDriver standard yet, which selenium uses. Therefore we should hold off on testing the latest versions of firefox until they've completed their implementation. The implementation progress is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=721859
I've also gotten rid of the tests of chrome version 58.0 since the difference between it and 59.0 is insignificant and the extra tests were pushing us towards our daily limit.
> Only test firefox version 47.0. Only test two versions of chrome.

- selenium/src/test/java/au/org/emii/portal/tests/ImosLinkCheckTest.java
- selenium/src/test/java/au/org/emii/portal/tests/step1/ExpandCollapseLargeRecordTest.java
- selenium/src/test/java/au/org/emii/portal/tests/step3/DownloadOptionsTest.java
- selenium/src/test/java/au/org/emii/portal/utils/PortalUtil.java
- selenium/src/test/java/au/org/emii/portal/utils/SeleniumUtil.java
See my explanation of the issue at https://github.com/aodn/aodn-portal/issues/2548#issuecomment-352963115
This should make the test _pass_ when we run it on our local machines and _fail_ when it's run on jenkins, because of catalogue-systest only being available from our locals.
> Fix ImosLinkCheckTest so it actually catches broken links

- selenium/pom.xml
- selenium/src/test/java/au/org/emii/portal/tests/BaseTest.java
- selenium/src/test/java/au/org/emii/portal/tests/step1/FreeTextSearchTest.java
This test enters a search term in the Keyword search box. 
To confirm that the results are valid, the test gets the 'more' link (external link to the metadata record) and massages it into a proxied request to geonetwork using the xml search endpoint. The resulting xml document is scanned for the search term (i.e. to make sure that the record really should appear in the results).
There is an issue that selenium does not like to work with xml pages and as a result it can read the page content okay for Chrome but not for firefox. So... I've used a 'SkipFirefox' directive for this test as I don't think there's a fix for this.
> added test for step1 FreeTextSearch

- src/test/javascript/portal/filter/GeometryFilterSpec.js
- web-app/js/portal/lang/en.js
Minor UI changes as part of [backlog issue #762](https://github.com/aodn/backlog/issues/762)
Peter and Phil had a discussion and decided that some facet labels on Step 2 would change so:
- 'Spatial Subset' -> 'Spatial'
- 'Temporal Extent' -> 'Temporal'
- 'Filters' -> 'Others'
I investigated whether changing the size of these labels was feasible but there aren't any good css selectors to make use of to target these (without risking the style change leaking out into other parts of the page/site)
> updated labels

- grails-app/controllers/au/org/emii/portal/AsyncDownloadController.groovy
- grails-app/services/au/org/emii/portal/GogoduckService.groovy
- grails-app/services/au/org/emii/portal/WpsAwsService.groovy
- src/groovy/au/org/emii/portal/proxying/ProxiedRequest.groovy
- test/unit/au/org/emii/portal/AsyncDownloadControllerTests.groovy
Will send X-Forwarded-For HTTP header containing the remote client IP address as the first entry (that header contains a list of IP Addresses) to the AWS WPS endpoint.  This can then be used to filter requests as being internal or external in SumoLogic.
> Send x forwarded for http header

- grails-app/taglib/au/org/emii/portal/MessageOfTheDayTagLib.groovy
- grails-app/views/_motd.gsp
- grails-app/views/landing/index.gsp
- src/groovy/au/org/emii/portal/PortalBranding.groovy
- test/unit/au/org/emii/portal/MessageOfTheDayTagLibTests.groovy
Add an accessible url to portal's config.groovy `motdUrl` Eg: https://s3-ap-southeast-2.amazonaws.com/static.emii.org.au/portalMotd/index.txt
The plain text file should contain two plain text lines. The portal will show a modal popup on the front page.
See https://github.com/aodn/static.emii.org.au_site/pull/13
> Fix for MOTD on home page without ExtJS

- src/groovy/au/org/emii/portal/wms/CoreGeoserverServer.groovy
- test/unit/au/org/emii/portal/wms/CoreGeoserverServerTests.groovy
Geowebcache can't proxy WFS/WPS requests as they do not have an associated layer.   Workaround this by using the WMS DescribeLayer request (which Geowebcache does proxy) to source the backing wfs server.   Alternative to defining backing server details in knownhosts or in the metadata.
> Use DescribeLayer to get linked wfs server

- grails-app/views/_js_includes.gsp
- src/test/javascript/portal/cart/NcWmsInjectorSpec.js
- src/test/javascript/portal/filter/FilterSpec.js
- src/test/javascript/portal/filter/GeometryFilterSpec.js
- src/test/javascript/portal/prototypes/OpenLayersSpec.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/filter/Filter.js
- web-app/js/portal/filter/StringDepthFilter.js
- web-app/js/portal/filter/ui/GroupPanel.js
- web-app/js/portal/prototypes/OpenLayers.js
Updated display of subset parameters selected on Step 3 to be the following format:
Spatial: From Lat/Lon -43.639, 132.715 to Lat/Lon -35.377, 136.582
Temporal: 2009-Jan-01-00:00-UTC to 2009-Jan-08-00:00-UTC
Depth: 0m to 5000m
> Adjust spatial filter display on Step 3.  Fixes #2704

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/groovy/au/org/emii/portal/HostVerifier.groovy
- src/test/javascript/portal/data/LayerStoreSpec.js
- test/unit/au/org/emii/portal/LayerControllerTests.groovy
- web-app/js/portal/data/LayerStore.js
- web-app/js/portal/ui/openlayers/LayerOptions.js
For https://github.com/aodn/backlog/issues/919
Here is some example config to drive testing. 
```
// testing with aodn namespacing
datalayerServer = [
uri: "http://geoserver-static.aodn.org.au/geoserver/aodn/wms",
wmsVersion: '1.1.1'
]
datalayers = [
[
name: "aodn:sw_region_kefs_points",
title: "sw_region_kefs_points",
server: datalayerServer
],
[
name: "aodn:cs_kefs_2011",
title: "cs_kefs_2011",
server: datalayerServer
]
]
```
> DataLayers can be loaded from config. Chosen via the picker

- web-app/js/portal/ui/FeatureInfoPopup.js
Spotted a trivial error when large images occur in GFI. They were not resizing because the popup tab container may not rendered yet if it is not the first tab.
Test this with `IMOS - AATAMS Facility - Satellite Relay Tagging Program - Near real-time CTD profile data` and some other layer
> Resize of large images now onRender of popup results

- src/groovy/au/org/emii/portal/wms/NcwmsServer.groovy
- src/test/javascript/portal/details/StylePanelSpec.js
- src/test/javascript/portal/ui/openlayers/layer/NcWmsSpec.js
- web-app/js/portal/details/StylePanel.js
- web-app/js/portal/ui/openlayers/layer/NcWms.js
Its used by geoserver to determine what parsers to use and its the only way we can tell geoserver to use different parsers for the WMS palette request parameter and the ncwms palette request parameter
> Let geoserver know what services we are talking to

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- src/groovy/au/org/emii/portal/wms/AlaServer.groovy
- src/groovy/au/org/emii/portal/wms/CoreGeoserverServer.groovy
- src/groovy/au/org/emii/portal/wms/FeatureCountService.groovy
- src/groovy/au/org/emii/portal/wms/NcwmsServer.groovy
- src/groovy/au/org/emii/portal/wms/WmsServer.groovy
- src/test/javascript/portal/filter/ui/FilterGroupPanelSpec.js
- test/unit/au/org/emii/portal/wms/CoreGeoserverServerTests.groovy
- web-app/js/portal/data/DataCollection.js
- web-app/js/portal/filter/ui/FilterGroupPanel.js
Geowebcache, we would inform the user the filter selection they had just made would result in an empty download.  Geowebcache does not pass through the getFeatureInfo checks and therefore broke the check. 
This changes the getFeatureInfo check previously being made on the WMS Layer into a GetFeature count check for Geoserver servers.
The implied feature request in aodn/backlog#49 would have required extensive changes to the filters to have all filters reload available options in response to a user applying a filter. complications would have arisen also from users adding a global spatial filter after layer filters are already applied.
Fixes aodn/backlog#49
> Working getFeature check on user filter selection

- src/groovy/au/org/emii/portal/wms/WmsServer.groovy
- web-app/js/portal/filter/ui/FilterGroupPanel.js
Changes to WmsServer.groovy stop errors being swallowed
Changes to FilterGroupPanel.js mean that the checkFilters request which checks the WMS layers WFS endpoint will use the temporal fields from the WMS layer not the 'TIME' field on the corresponding data layer
> CheckFilters now uses WMS layer date fields

- web-app/js/portal/search/FacetedSearchResultsDataView.js
instead of specific schema conversion service
> Use schema agnostic get.portal to update popularity

- src/test/javascript/portal/filter/ui/AlaSpeciesFilterPanelSpec.js
- web-app/js/portal/filter/ui/AlaSpeciesFilterPanel.js
If testing these changes note that by quickly interacting with it (therefore making map updates) you may cause both the ALA WMS and autocomplete endpoints to stop responding.
The way this component has broken in the past is:
1. The empty text should alway disappear on enter
1. The spinner below the input box should always show after typing at least three letters
> Makes the ALA autocomplete widget un-muntable

- grails-app/conf/Config.groovy
@pmbohm would you mind PRing this one? 
Now that the filters for the two collections are in the filter-config repo (test) branch you can test by pointing your local portal to catalogue-sandbox and searching for these two:
- CSIRO O&A CTD Data Overview (1982 - present) 
- CSIRO O&A Hydrology Data Overview (1942 - present)
With this change, the filters should appear and values are populated.
I looked at the download handler but I decided not to proceed with anything because I couldn't get a download to work in sandbox thus testing would be pretty useless.
> changes csiro type from 'dataTrawler' to 'GeoserverFilterConfig'

- grails-app/services/au/org/emii/portal/JsonService.groovy
- src/test/javascript/portal/cart/AsyncDownloadHandlerSpec.js
- src/test/javascript/portal/cart/DownloaderSpec.js
- src/test/javascript/portal/cart/GaDownloadHandlerSpec.js
- web-app/css/AODNTheme.css
- web-app/js/portal/cart/AsyncDownloadHandler.js
- web-app/js/portal/cart/Downloader.js
- web-app/js/portal/cart/GaDownloadHandler.js
- web-app/js/portal/lang/en.js
Fixes https://github.com/aodn/aodn-portal/issues/2762
downloadHandlers inherriting from AsyncDownloadHandler.js can now handle when the response is 200 but contains a known error message in the responseText
> Allow tailored response (error) handling for async downloads

- src/test/javascript/portal/cart/NcWmsInjectorSpec.js
- src/test/javascript/portal/details/NcWmsPanelSpec.js
- web-app/js/portal/cart/NcWmsInjector.js
- web-app/js/portal/details/NcWmsPanel.js
- web-app/js/portal/form/UtcExtentDateTime.js
- web-app/js/portal/lang/en.js
Fixes #2680
Fixes https://github.com/aodn/backlog/issues/901
The functionality:
1. `UtcExtentDateTime` datePicker errors now bubble up to `errorMessages` on the ncwmsDateParams filter
1. The error messages manifest differently in the Step 3 filter info and the disabled download button message. The `warningEmptyDownloadMessage` in Step 2 will be shown.
1. There is no longer defaulting to the data collections full extent.
1. The nearest neighbour behaviour remains. If the date component passes validation a download is possible
1. ncWMS filter handling remains as dangerous as ever
> ncWMS temporal selections must be valid

- grails-app/conf/Config.groovy
More work on https://github.com/aodn/issues/issues/361
The autocomplete search is now coming from another places and works just fine, while leaving the WMS server to fall over all by itself
> Test url for ALA autocomplete search

- Jenkinsfile
- bumpversion.sh
Reverts aodn/aodn-portal#2820
Oh no. This causes an infinite loop of jenkins builds.
> Revert "Fix jenkins git credentials for release"

- grails-app/conf/Config.groovy
- grails-app/controllers/au/org/emii/portal/DownloadController.groovy
- grails-app/services/au/org/emii/portal/BulkDownloadService.groovy
Notes:  The changes in DownloadController.groovy correct some borken logic in the exception handling.  This is sufficient to fix things on a local Portal instance.
The additional changes in BulkDownloadService.groovy were necessary to catch the ClientAbortException when the application is deployed to aws.  The reason for this difference is unknown.
In BulkDownloadService we first catch the exception while copying bytes to the ZipStream so that it is not handled by the following ``catch (Exception e)``.  This immediately rethrows the exception to exit the loop writing files to the ZipStream so no further files are attempted.
> Handle ClientAbortExceptions

- grails-app/conf/Config.groovy
Reverts https://github.com/aodn/aodn-portal/pull/2565
This is no longer required. Once merged, we can then revert the changes made in https://github.com/aodn/schema-plugins/pull/53 to add the new protocol.
> Remove AODN:WFS-EXTERNAL-1.0.0-http-get-capabilities from Config.groovy

- src/test/javascript/portal/details/InfoPanelSpec.js
- web-app/js/portal/details/InfoPanel.js
Due to display issues in GeoNetwork 3, the description element (title)
was moved to the name element when the name element was empty
during the data migration.
To handle both GN2 and GN3 check the name element if the title element is empty
before using unnamed resource literal
> Fixes aodn/backlog#1780

- src/test/javascript/portal/search/FacetedSearchResultsDataViewSpec.js
- web-app/js/portal/search/FacetedSearchResultsDataView.js
This fixes in GN3, collections without <tempExtentEnd> do not show end date as current date in portal (does with GN2)
GN2 search returns the current date when no date is present whereas GN3 does not so we let the Portal take care of it.
> Always return current year when no date given

- grails-app/controllers/au/org/emii/portal/LayerController.groovy
- web-app/js/portal/details/DataCollectionDetailsPanel.js
Backlog item: https://github.com/aodn/backlog/issues/3253
The gist of this PR is that the portal will now capture the number of errors that a layer produces. Once the layer has finished loading all tiles if any of them failed it will log an error.
> Log collection issues for Portal

- web-app/js/aws-cognito/UserAuthentication.js
The `deleteUser` callback is incorrect meaning that the user cookie is never deleted after account deletion.
> Fix cookie not being cleared after account delete

- grails-app/views/auth/_signUpModal.gsp
The "see more information here" link is pointing to the terms of use page until the new page is made available by IMOS Admin.
> Register dialog: Update links and labels

- web-app/js/portal/filter/combiner/SpatialSubsetIntersectTester.js
Effectively we assume the whole world is the extent and return 'true'. Apologies for the messy nesting of the `if`, this is to allow tests to pass.
> Allow for no spatial extent in records

- grails-app/conf/Config.groovy
You can test it by connect to https://catalogue-rc.aodn.org.au, this item have set to use OGC:WMS
https://catalogue-rc.aodn.org.au/geonetwork/srv/eng/catalog.search#/metadata/34a628d2-ff7e-4362-85c0-72960c0056bd/formatters/xml_view_aodn?xsl=none
If you see it appear in the search list then it works
> [4003] Update config to allow new protocol
